// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnicoreCRM.Crm.Customers.Infrastructure.Persistence;

#nullable disable

namespace UnicoreCRM.Crm.Customers.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    [Migration("20260829053302_CustomersRequiredEnumConstraints")]
    partial class CustomersRequiredEnumConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customers")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnicoreCRM.Crm.Customers.Domain.Customer", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CustomerCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTimeOffset>("FirstPurchaseAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Health")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("LastPurchaseAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelationshipId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RelationshipType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("WorkspaceId", "CustomerId");

                    b.HasIndex("WorkspaceId", "CreatedAt", "CustomerId")
                        .IsDescending(false, true, false);

                    b.HasIndex("WorkspaceId", "RelationshipType", "RelationshipId")
                        .IsUnique();

                    b.ToTable("Customers", "customers", t =>
                        {
                            t.HasCheckConstraint("CK_Customers_Health", "(([Health] COLLATE Latin1_General_100_BIN2 = N'GOOD' AND DATALENGTH([Health]) = DATALENGTH(N'GOOD')) OR ([Health] COLLATE Latin1_General_100_BIN2 = N'WATCH' AND DATALENGTH([Health]) = DATALENGTH(N'WATCH')) OR ([Health] COLLATE Latin1_General_100_BIN2 = N'RISK' AND DATALENGTH([Health]) = DATALENGTH(N'RISK')))");

                            t.HasCheckConstraint("CK_Customers_RelationshipType", "(([RelationshipType] COLLATE Latin1_General_100_BIN2 = N'CONTACT' AND DATALENGTH([RelationshipType]) = DATALENGTH(N'CONTACT')) OR ([RelationshipType] COLLATE Latin1_General_100_BIN2 = N'ORGANIZATION_ACCOUNT' AND DATALENGTH([RelationshipType]) = DATALENGTH(N'ORGANIZATION_ACCOUNT')))");

                            t.HasCheckConstraint("CK_Customers_Status", "(([Status] COLLATE Latin1_General_100_BIN2 = N'NEW' AND DATALENGTH([Status]) = DATALENGTH(N'NEW')) OR ([Status] COLLATE Latin1_General_100_BIN2 = N'ACTIVE' AND DATALENGTH([Status]) = DATALENGTH(N'ACTIVE')) OR ([Status] COLLATE Latin1_General_100_BIN2 = N'AT_RISK' AND DATALENGTH([Status]) = DATALENGTH(N'AT_RISK')) OR ([Status] COLLATE Latin1_General_100_BIN2 = N'INACTIVE' AND DATALENGTH([Status]) = DATALENGTH(N'INACTIVE')) OR ([Status] COLLATE Latin1_General_100_BIN2 = N'CHURNED' AND DATALENGTH([Status]) = DATALENGTH(N'CHURNED')) OR ([Status] COLLATE Latin1_General_100_BIN2 = N'DO_NOT_CONTACT' AND DATALENGTH([Status]) = DATALENGTH(N'DO_NOT_CONTACT')) OR ([Status] COLLATE Latin1_General_100_BIN2 = N'ARCHIVED' AND DATALENGTH([Status]) = DATALENGTH(N'ARCHIVED')))");

                            t.HasCheckConstraint("CK_Customers_Type", "(([Type] COLLATE Latin1_General_100_BIN2 = N'B2C' AND DATALENGTH([Type]) = DATALENGTH(N'B2C')) OR ([Type] COLLATE Latin1_General_100_BIN2 = N'B2B' AND DATALENGTH([Type]) = DATALENGTH(N'B2B')))");
                        });
                });

            modelBuilder.Entity("UnicoreCRM.Crm.Customers.Domain.CustomerReadAuditRecord", b =>
                {
                    b.Property<string>("AuditId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("CustomerVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AuditId");

                    b.HasIndex("WorkspaceId", "OccurredAt");

                    b.HasIndex("WorkspaceId", "CustomerId", "OccurredAt");

                    b.ToTable("ReadAuditRecords", "customers");
                });
#pragma warning restore 612, 618
        }
    }
}
