using UnicoreCRM.Crm.Contacts.Contracts;
using UnicoreCRM.Crm.Organizations.Application.Common;
using UnicoreCRM.Crm.Organizations.Contracts;
using UnicoreCRM.Crm.Organizations.Domain;
namespace UnicoreCRM.Crm.Organizations.Application.GetOrganizationOverview;
internal sealed record Query(string OrganizationId,OrganizationRequestMetadata Metadata);
internal sealed class Handler(OrganizationAuthorization authorization,IOrganizationsPersistence persistence,IOrganizationContactReadParticipant contacts,TimeProvider timeProvider)
{
 internal async Task<OrganizationOperationResult<OrganizationOverviewReadModel>> HandleAsync(Query query,CancellationToken ct){var access=await authorization.AuthorizeAsync(query.Metadata,ct);if(!access.IsSuccess)return OrganizationOperationResult<OrganizationOverviewReadModel>.Failure(access.Error!);var organization=await persistence.ReadOrganizationAsync(access.Value!.Trusted.WorkspaceId,query.OrganizationId,ct);if(organization is null)return OrganizationOperationResult<OrganizationOverviewReadModel>.Failure(OrganizationErrors.NotFound());var denied=await authorization.EnforceRecordAsync(access.Value,organization,"getOrganizationOverview",query.Metadata,ct);if(denied is not null)return OrganizationOperationResult<OrganizationOverviewReadModel>.Failure(denied);var ids=await contacts.ReadVisibleActiveContactIdsAsync(access.Value.Trusted,organization.OrganizationId,query.Metadata.RequestId,query.Metadata.CorrelationId,ct);var allowed=new List<string>();if(organization.Status!="archived"){allowed.Add("updateOrganization");allowed.Add("archiveOrganization");}var now=timeProvider.GetUtcNow();persistence.AddReadAudit(new OrganizationReadAuditRecord("getOrganizationOverview",access.Value.Trusted.WorkspaceId,access.Value.Trusted.MemberId,organization.OrganizationId,query.Metadata.RequestId,query.Metadata.CorrelationId,organization.Version,now));await persistence.SaveChangesAsync(ct);var doc=OrganizationFieldSecurity.Project(OrganizationProjection.Document(organization),access.Value.Authorization);return OrganizationOperationResult<OrganizationOverviewReadModel>.Success(new(doc,ids,new(ids.Count),[],allowed,organization.Version,OrganizationProjection.TimestampValue(now)));}
}
