namespace UnicoreCRM.Integrations.Webhooks.Outbound.Domain;

internal sealed class OutboundWebhookSubscription
{
    private OutboundWebhookSubscription(){}
    internal OutboundWebhookSubscription(string workspaceId,string name,string eventType,string endpoint,string protectedSecret,string actor,DateTimeOffset now){SubscriptionId=$"webhook_{Guid.NewGuid():N}";WorkspaceId=workspaceId;Name=name;EventType=eventType;EndpointUrl=endpoint;Status="DRAFT";Version=0;ProtectedSecret=protectedSecret;CreatedBy=UpdatedBy=actor;CreatedAt=UpdatedAt=now;}
    internal string SubscriptionId{get;private set;}=null!;internal string WorkspaceId{get;private set;}=null!;internal string Name{get;private set;}=null!;internal string EventType{get;private set;}=null!;internal string EndpointUrl{get;private set;}=null!;internal string Status{get;private set;}=null!;internal long Version{get;private set;}internal string ProtectedSecret{get;private set;}=null!;internal string CreatedBy{get;private set;}=null!;internal DateTimeOffset CreatedAt{get;private set;}internal string UpdatedBy{get;private set;}=null!;internal DateTimeOffset UpdatedAt{get;private set;}internal DateTimeOffset? ArchivedAt{get;private set;}
    internal void Update(string name,string eventType,string endpoint,string actor,DateTimeOffset now){RequireEditable();Name=name;EventType=eventType;EndpointUrl=endpoint;Touch(actor,now);}
    internal void Activate(string actor,DateTimeOffset now){if(Status!="DRAFT")throw new InvalidOperationException("Only DRAFT can activate.");Status="ACTIVE";Touch(actor,now);} internal void Pause(string actor,DateTimeOffset now){if(Status!="ACTIVE")throw new InvalidOperationException("Only ACTIVE can pause.");Status="PAUSED";Touch(actor,now);} internal void Resume(string actor,DateTimeOffset now){if(Status!="PAUSED")throw new InvalidOperationException("Only PAUSED can resume.");Status="ACTIVE";Touch(actor,now);} internal void Archive(string actor,DateTimeOffset now){if(Status=="ARCHIVED")throw new InvalidOperationException("Already archived.");Status="ARCHIVED";ArchivedAt=now;Touch(actor,now);}internal void Rotate(string secret,string actor,DateTimeOffset now){if(Status=="ARCHIVED")throw new InvalidOperationException("Archived subscription is immutable.");ProtectedSecret=secret;Touch(actor,now);}
    private void RequireEditable(){if(Status is not("DRAFT" or "PAUSED"))throw new InvalidOperationException("Pause the subscription before editing endpoint or event identity.");}private void Touch(string actor,DateTimeOffset now){Version++;UpdatedBy=actor;UpdatedAt=now;}
}

internal sealed class OutboundWebhookConsumerCursor{private OutboundWebhookConsumerCursor(){}internal OutboundWebhookConsumerCursor(string id,long sequence,DateTimeOffset now){ConsumerId=id;LastProcessedSequence=sequence;CreatedAt=UpdatedAt=now;}internal string ConsumerId{get;private set;}=null!;internal long LastProcessedSequence{get;private set;}internal DateTimeOffset CreatedAt{get;private set;}internal DateTimeOffset UpdatedAt{get;private set;}internal byte[] RowVersion{get;private set;}=[];internal void Advance(long sequence,DateTimeOffset now){if(sequence<LastProcessedSequence)throw new InvalidOperationException("Cursor cannot move backwards.");LastProcessedSequence=sequence;UpdatedAt=now;}}

internal sealed class OutboundWebhookDelivery{private OutboundWebhookDelivery(){}internal OutboundWebhookDelivery(OutboundWebhookSubscription s,string eventId,long sequence,string eventType,string payload,DateTimeOffset now){DeliveryId=$"delivery_{Guid.NewGuid():N}";SubscriptionId=s.SubscriptionId;WorkspaceId=s.WorkspaceId;EventId=eventId;EventSequence=sequence;EventType=eventType;CanonicalPayloadJson=payload;Status="PENDING";NextAttemptAt=now;CreatedAt=now;}internal string DeliveryId{get;private set;}=null!;internal string SubscriptionId{get;private set;}=null!;internal string WorkspaceId{get;private set;}=null!;internal string EventId{get;private set;}=null!;internal long EventSequence{get;private set;}internal string EventType{get;private set;}=null!;internal string CanonicalPayloadJson{get;private set;}=null!;internal string Status{get;private set;}=null!;internal int AttemptCount{get;private set;}internal DateTimeOffset NextAttemptAt{get;private set;}internal string? ExecutionAttemptId{get;private set;}internal DateTimeOffset? LeaseExpiresAt{get;private set;}internal DateTimeOffset? LastAttemptAt{get;private set;}internal int? LastHttpStatus{get;private set;}internal string? LastErrorCode{get;private set;}internal DateTimeOffset CreatedAt{get;private set;}internal DateTimeOffset? SucceededAt{get;private set;}internal DateTimeOffset? DeadLetteredAt{get;private set;}
 internal void Lease(string id,DateTimeOffset now,DateTimeOffset until){Status="IN_FLIGHT";ExecutionAttemptId=id;LeaseExpiresAt=until;AttemptCount++;LastAttemptAt=now;}internal bool Owns(string id)=>Status=="IN_FLIGHT"&&ExecutionAttemptId==id;internal void Succeed(string id,DateTimeOffset now,int status){Require(id);Status="SUCCEEDED";SucceededAt=now;LastHttpStatus=status;Clear();}internal void Fail(string id,DateTimeOffset now,int? status,string code,bool retryable){Require(id);LastHttpStatus=status;LastErrorCode=code;if(retryable&&AttemptCount<6){Status="RETRY_SCHEDULED";NextAttemptAt=now.Add(RetryDelay(AttemptCount+1));}else{Status="DEAD_LETTER";DeadLetteredAt=now;}Clear();}internal void Replay(DateTimeOffset now){if(Status!="DEAD_LETTER")throw new InvalidOperationException("Only dead-letter deliveries can be replayed.");Status="PENDING";AttemptCount=0;NextAttemptAt=now;DeadLetteredAt=null;LastErrorCode=null;LastHttpStatus=null;}private void Require(string id){if(!Owns(id))throw new InvalidOperationException("Stale delivery execution attempt.");}private void Clear(){ExecutionAttemptId=null;LeaseExpiresAt=null;}private static TimeSpan RetryDelay(int attempt)=>attempt switch{2=>TimeSpan.FromMinutes(1),3=>TimeSpan.FromMinutes(5),4=>TimeSpan.FromMinutes(15),5=>TimeSpan.FromHours(1),6=>TimeSpan.FromHours(6),_=>TimeSpan.Zero};}

internal sealed class OutboundWebhookDeliveryAttempt{private OutboundWebhookDeliveryAttempt(){}internal OutboundWebhookDeliveryAttempt(string attemptId,string deliveryId,int number,DateTimeOffset started){AttemptId=attemptId;DeliveryId=deliveryId;AttemptNumber=number;StartedAt=started;}internal string AttemptId{get;private set;}=null!;internal string DeliveryId{get;private set;}=null!;internal int AttemptNumber{get;private set;}internal DateTimeOffset StartedAt{get;private set;}internal DateTimeOffset? CompletedAt{get;private set;}internal string? Outcome{get;private set;}internal int? HttpStatus{get;private set;}internal string? ErrorCode{get;private set;}internal void Complete(DateTimeOffset now,string outcome,int? status,string? error){CompletedAt=now;Outcome=outcome;HttpStatus=status;ErrorCode=error;}}
internal sealed class OutboundWebhookIdempotency{private OutboundWebhookIdempotency(){}internal OutboundWebhookIdempotency(string scope,string workspace,string operation,string key,string fingerprint,string response,DateTimeOffset now){ScopeKey=scope;WorkspaceId=workspace;Operation=operation;IdempotencyKey=key;Fingerprint=fingerprint;ResponseJson=response;CreatedAt=now;}internal string ScopeKey{get;private set;}=null!;internal string WorkspaceId{get;private set;}=null!;internal string Operation{get;private set;}=null!;internal string IdempotencyKey{get;private set;}=null!;internal string Fingerprint{get;private set;}=null!;internal string ResponseJson{get;private set;}=null!;internal DateTimeOffset CreatedAt{get;private set;}}
internal sealed class OutboundWebhookAudit{private OutboundWebhookAudit(){}internal OutboundWebhookAudit(string workspace,string actor,string action,string target,string correlation,DateTimeOffset now){AuditId=$"webhook_audit_{Guid.NewGuid():N}";WorkspaceId=workspace;ActorId=actor;Action=action;TargetId=target;CorrelationId=correlation;OccurredAt=now;}internal string AuditId{get;private set;}=null!;internal string WorkspaceId{get;private set;}=null!;internal string ActorId{get;private set;}=null!;internal string Action{get;private set;}=null!;internal string TargetId{get;private set;}=null!;internal string CorrelationId{get;private set;}=null!;internal DateTimeOffset OccurredAt{get;private set;}}
