// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnicoreCRM.Sales.Quotes.Infrastructure.Persistence;

#nullable disable

namespace UnicoreCRM.Sales.Quotes.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(QuotesDbContext))]
    [Migration("20260831063817_QuotesReadAudit")]
    partial class QuotesReadAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("quotes")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnicoreCRM.Sales.Quotes.Domain.Quote", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("QuoteId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdjustmentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ApprovalContentFingerprint")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ApprovalDecisionNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("ApprovalPolicyVersion")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("ApprovalReasonsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ApprovalRequestedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ApprovalRequestedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool?>("ApprovalRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ApprovalStatus")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ApprovedBy")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BuyerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("ContactId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("DeliveryHistoryJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountTotalAmount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("DiscountTotalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset?>("ExpiredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<decimal>("GrandTotalAmount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("GrandTotalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("LineItemsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PaymentAgreementJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QuoteNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("QuoteRevision")
                        .HasColumnType("int");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<long>("ResourceVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("ReviewRequestedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("RevisionOfQuoteId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RootQuoteId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SenderAddress")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("SenderEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("SenderName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("SenderTaxId")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("SourceDealId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceLeadId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourcePath")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("SubtotalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<decimal>("TaxTotalAmount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("TaxTotalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateOnly?>("ValidUntil")
                        .HasColumnType("date");

                    b.HasKey("WorkspaceId", "QuoteId");

                    b.HasIndex("WorkspaceId", "SourceDealId");

                    b.HasIndex("WorkspaceId", "Status");

                    b.HasIndex("WorkspaceId", "BuyerType", "BuyerId");

                    b.HasIndex("WorkspaceId", "CreatedAt", "QuoteId")
                        .IsDescending(false, true, false);

                    b.HasIndex("WorkspaceId", "GrandTotalAmount", "QuoteId");

                    b.HasIndex("WorkspaceId", "QuoteNumber", "QuoteId");

                    b.HasIndex("WorkspaceId", "UpdatedAt", "QuoteId")
                        .IsDescending(false, true, false);

                    b.HasIndex("WorkspaceId", "ValidUntil", "QuoteId");

                    b.ToTable("Quotes", "quotes", t =>
                        {
                            t.HasCheckConstraint("CK_Quotes_ActionsJson", "ISJSON([ActionsJson]) = 1");

                            t.HasCheckConstraint("CK_Quotes_AdjustmentsJson", "[AdjustmentsJson] IS NULL OR ISJSON([AdjustmentsJson]) = 1");

                            t.HasCheckConstraint("CK_Quotes_ApprovalReasonsJson", "[ApprovalReasonsJson] IS NULL OR ISJSON([ApprovalReasonsJson]) = 1");

                            t.HasCheckConstraint("CK_Quotes_ApprovalStatus", "[ApprovalStatus] IS NULL OR ((([ApprovalStatus] COLLATE Latin1_General_100_BIN2 = N'NOT_REQUIRED' AND DATALENGTH([ApprovalStatus]) = DATALENGTH(N'NOT_REQUIRED')) OR ([ApprovalStatus] COLLATE Latin1_General_100_BIN2 = N'PENDING' AND DATALENGTH([ApprovalStatus]) = DATALENGTH(N'PENDING')) OR ([ApprovalStatus] COLLATE Latin1_General_100_BIN2 = N'APPROVED' AND DATALENGTH([ApprovalStatus]) = DATALENGTH(N'APPROVED')) OR ([ApprovalStatus] COLLATE Latin1_General_100_BIN2 = N'CHANGES_REQUESTED' AND DATALENGTH([ApprovalStatus]) = DATALENGTH(N'CHANGES_REQUESTED'))))");

                            t.HasCheckConstraint("CK_Quotes_BuyerType", "(([BuyerType] COLLATE Latin1_General_100_BIN2 = N'CONTACT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'CONTACT')) OR ([BuyerType] COLLATE Latin1_General_100_BIN2 = N'ORGANIZATION_ACCOUNT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'ORGANIZATION_ACCOUNT')))");

                            t.HasCheckConstraint("CK_Quotes_DeliveryHistoryJson", "[DeliveryHistoryJson] IS NULL OR ISJSON([DeliveryHistoryJson]) = 1");

                            t.HasCheckConstraint("CK_Quotes_LineItemsJson", "ISJSON([LineItemsJson]) = 1");

                            t.HasCheckConstraint("CK_Quotes_PaymentAgreementJson", "[PaymentAgreementJson] IS NULL OR ISJSON([PaymentAgreementJson]) = 1");

                            t.HasCheckConstraint("CK_Quotes_QuoteRevision", "[QuoteRevision] >= 1");

                            t.HasCheckConstraint("CK_Quotes_ResourceVersion", "[ResourceVersion] >= 0");

                            t.HasCheckConstraint("CK_Quotes_SourcePath", "(([SourcePath] COLLATE Latin1_General_100_BIN2 = N'DEAL' AND DATALENGTH([SourcePath]) = DATALENGTH(N'DEAL')) OR ([SourcePath] COLLATE Latin1_General_100_BIN2 = N'DIRECT_SALE' AND DATALENGTH([SourcePath]) = DATALENGTH(N'DIRECT_SALE')))");

                            t.HasCheckConstraint("CK_Quotes_Status", "(([Status] COLLATE Latin1_General_100_BIN2 = N'DRAFT' AND DATALENGTH([Status]) = DATALENGTH(N'DRAFT')) OR ([Status] COLLATE Latin1_General_100_BIN2 = N'REVIEW' AND DATALENGTH([Status]) = DATALENGTH(N'REVIEW')) OR ([Status] COLLATE Latin1_General_100_BIN2 = N'SENT' AND DATALENGTH([Status]) = DATALENGTH(N'SENT')) OR ([Status] COLLATE Latin1_General_100_BIN2 = N'ACCEPTED' AND DATALENGTH([Status]) = DATALENGTH(N'ACCEPTED')) OR ([Status] COLLATE Latin1_General_100_BIN2 = N'REJECTED' AND DATALENGTH([Status]) = DATALENGTH(N'REJECTED')) OR ([Status] COLLATE Latin1_General_100_BIN2 = N'EXPIRED' AND DATALENGTH([Status]) = DATALENGTH(N'EXPIRED')))");
                        });
                });

            modelBuilder.Entity("UnicoreCRM.Sales.Quotes.Domain.QuoteReadAuditRecord", b =>
                {
                    b.Property<string>("AuditId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("RecordId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("ResourceVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AuditId");

                    b.HasIndex("WorkspaceId", "OccurredAt");

                    b.ToTable("ReadAuditRecords", "quotes", t =>
                        {
                            t.HasCheckConstraint("CK_ReadAuditRecords_Outcome", "(([Outcome] COLLATE Latin1_General_100_BIN2 = N'READ' AND DATALENGTH([Outcome]) = DATALENGTH(N'READ')))");

                            t.HasCheckConstraint("CK_ReadAuditRecords_ResourceVersion", "[ResourceVersion] IS NULL OR [ResourceVersion] >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
