// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnicoreCRM.Billing.Invoices.Infrastructure.Persistence;

#nullable disable

namespace UnicoreCRM.Billing.Invoices.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(InvoicesDbContext))]
    [Migration("20260831060703_InvoicesReadCore")]
    partial class InvoicesReadCore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("invoices")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnicoreCRM.Billing.Invoices.Domain.Invoice", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("InvoiceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BuyerSnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreationIntentId")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("DeliveryState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset?>("DiscardedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<string>("ExchangeRateSnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("InvoiceNumber")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateOnly?>("IssueDate")
                        .HasColumnType("date");

                    b.Property<string>("IssueEvidenceJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IssueFailureCode")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<DateTimeOffset?>("IssuedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("LinesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerms")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("ResourceVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("SellerSnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceLinksJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TotalsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("VoidReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("VoidedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("WorkspaceId", "InvoiceId");

                    b.ToTable("Invoices", "invoices", t =>
                        {
                            t.HasCheckConstraint("CK_Invoices_BuyerSnapshotJson", "ISJSON([BuyerSnapshotJson]) = 1");

                            t.HasCheckConstraint("CK_Invoices_BuyerType", "(([BuyerType] COLLATE Latin1_General_100_BIN2 = N'CONTACT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'CONTACT')) OR ([BuyerType] COLLATE Latin1_General_100_BIN2 = N'ORGANIZATION_ACCOUNT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'ORGANIZATION_ACCOUNT')))");

                            t.HasCheckConstraint("CK_Invoices_Currency", "[Currency] LIKE '[A-Z][A-Z][A-Z]' COLLATE Latin1_General_100_BIN2 AND DATALENGTH([Currency]) = 6");

                            t.HasCheckConstraint("CK_Invoices_DeliveryState", "(([DeliveryState] COLLATE Latin1_General_100_BIN2 = N'NOT_SENT' AND DATALENGTH([DeliveryState]) = DATALENGTH(N'NOT_SENT')) OR ([DeliveryState] COLLATE Latin1_General_100_BIN2 = N'SENDING' AND DATALENGTH([DeliveryState]) = DATALENGTH(N'SENDING')) OR ([DeliveryState] COLLATE Latin1_General_100_BIN2 = N'SENT' AND DATALENGTH([DeliveryState]) = DATALENGTH(N'SENT')) OR ([DeliveryState] COLLATE Latin1_General_100_BIN2 = N'DELIVERY_FAILED' AND DATALENGTH([DeliveryState]) = DATALENGTH(N'DELIVERY_FAILED')))");

                            t.HasCheckConstraint("CK_Invoices_ExchangeRateSnapshotJson", "[ExchangeRateSnapshotJson] IS NULL OR ISJSON([ExchangeRateSnapshotJson]) = 1");

                            t.HasCheckConstraint("CK_Invoices_IdempotencyKey", "LEN([IdempotencyKey]) >= 8");

                            t.HasCheckConstraint("CK_Invoices_IssueEvidenceJson", "[IssueEvidenceJson] IS NULL OR ISJSON([IssueEvidenceJson]) = 1");

                            t.HasCheckConstraint("CK_Invoices_LifecycleState", "(([LifecycleState] COLLATE Latin1_General_100_BIN2 = N'DRAFT' AND DATALENGTH([LifecycleState]) = DATALENGTH(N'DRAFT')) OR ([LifecycleState] COLLATE Latin1_General_100_BIN2 = N'ISSUING' AND DATALENGTH([LifecycleState]) = DATALENGTH(N'ISSUING')) OR ([LifecycleState] COLLATE Latin1_General_100_BIN2 = N'ISSUED' AND DATALENGTH([LifecycleState]) = DATALENGTH(N'ISSUED')) OR ([LifecycleState] COLLATE Latin1_General_100_BIN2 = N'ISSUE_FAILED' AND DATALENGTH([LifecycleState]) = DATALENGTH(N'ISSUE_FAILED')) OR ([LifecycleState] COLLATE Latin1_General_100_BIN2 = N'DISCARDED' AND DATALENGTH([LifecycleState]) = DATALENGTH(N'DISCARDED')) OR ([LifecycleState] COLLATE Latin1_General_100_BIN2 = N'VOIDED' AND DATALENGTH([LifecycleState]) = DATALENGTH(N'VOIDED')))");

                            t.HasCheckConstraint("CK_Invoices_LinesJson", "ISJSON([LinesJson]) = 1");

                            t.HasCheckConstraint("CK_Invoices_ResourceVersion", "[ResourceVersion] >= 0");

                            t.HasCheckConstraint("CK_Invoices_SellerSnapshotJson", "ISJSON([SellerSnapshotJson]) = 1");

                            t.HasCheckConstraint("CK_Invoices_SourceLinksJson", "ISJSON([SourceLinksJson]) = 1");

                            t.HasCheckConstraint("CK_Invoices_TotalsJson", "ISJSON([TotalsJson]) = 1");
                        });
                });

            modelBuilder.Entity("UnicoreCRM.Billing.Invoices.Domain.InvoiceReadAuditRecord", b =>
                {
                    b.Property<string>("AuditId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("RecordId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("ResourceVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AuditId");

                    b.HasIndex("WorkspaceId", "OccurredAt");

                    b.ToTable("ReadAuditRecords", "invoices", t =>
                        {
                            t.HasCheckConstraint("CK_ReadAuditRecords_Outcome", "(([Outcome] COLLATE Latin1_General_100_BIN2 = N'READ' AND DATALENGTH([Outcome]) = DATALENGTH(N'READ')))");

                            t.HasCheckConstraint("CK_ReadAuditRecords_ResourceVersion", "[ResourceVersion] IS NULL OR [ResourceVersion] >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
