// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnicoreCRM.Sales.Orders.Infrastructure.Persistence;

#nullable disable

namespace UnicoreCRM.Sales.Orders.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OrdersDbContext))]
    [Migration("20260831062123_OrdersReadAudit")]
    partial class OrdersReadAudit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("orders")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnicoreCRM.Sales.Orders.Domain.Order", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OrderId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AdjustmentsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArchiveReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BuyerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ContactId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreditApprovalJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditPolicyEvaluationJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<decimal>("DiscountTotalAmount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("DiscountTotalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<DateOnly?>("ExpectedDeliveryDate")
                        .HasColumnType("date");

                    b.Property<decimal>("GrandTotalAmount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("GrandTotalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("LineItemsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateOnly>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RecipientEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("RecipientName")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("RecipientPhone")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<long>("ResourceVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("ShippingAddressJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceDealId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceLeadId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceQuoteId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceQuoteNumber")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("SubtotalAmount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("SubtotalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<decimal>("TaxTotalAmount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("TaxTotalCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("WorkspaceId", "OrderId");

                    b.HasIndex("WorkspaceId", "SourceDealId");

                    b.HasIndex("WorkspaceId", "SourceQuoteId");

                    b.HasIndex("WorkspaceId", "State");

                    b.HasIndex("WorkspaceId", "BuyerType", "BuyerId");

                    b.HasIndex("WorkspaceId", "CreatedAt", "OrderId");

                    b.HasIndex("WorkspaceId", "GrandTotalAmount", "OrderId");

                    b.HasIndex("WorkspaceId", "OrderDate", "OrderId");

                    b.HasIndex("WorkspaceId", "OrderNumber", "OrderId");

                    b.HasIndex("WorkspaceId", "UpdatedAt", "OrderId")
                        .IsDescending(false, true, true);

                    b.ToTable("Orders", "orders", t =>
                        {
                            t.HasCheckConstraint("CK_Orders_ActionsJson", "ISJSON([ActionsJson]) = 1");

                            t.HasCheckConstraint("CK_Orders_AdjustmentsJson", "[AdjustmentsJson] IS NULL OR ISJSON([AdjustmentsJson]) = 1");

                            t.HasCheckConstraint("CK_Orders_BuyerType", "(([BuyerType] COLLATE Latin1_General_100_BIN2 = N'CONTACT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'CONTACT')) OR ([BuyerType] COLLATE Latin1_General_100_BIN2 = N'ORGANIZATION_ACCOUNT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'ORGANIZATION_ACCOUNT')))");

                            t.HasCheckConstraint("CK_Orders_CreditApprovalJson", "[CreditApprovalJson] IS NULL OR ISJSON([CreditApprovalJson]) = 1");

                            t.HasCheckConstraint("CK_Orders_CreditPolicyEvaluationJson", "[CreditPolicyEvaluationJson] IS NULL OR ISJSON([CreditPolicyEvaluationJson]) = 1");

                            t.HasCheckConstraint("CK_Orders_LineItemsJson", "ISJSON([LineItemsJson]) = 1");

                            t.HasCheckConstraint("CK_Orders_ResourceVersion", "[ResourceVersion] >= 0");

                            t.HasCheckConstraint("CK_Orders_ShippingAddressJson", "[ShippingAddressJson] IS NULL OR ISJSON([ShippingAddressJson]) = 1");

                            t.HasCheckConstraint("CK_Orders_State", "(([State] COLLATE Latin1_General_100_BIN2 = N'DRAFT' AND DATALENGTH([State]) = DATALENGTH(N'DRAFT')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'CONFIRMED' AND DATALENGTH([State]) = DATALENGTH(N'CONFIRMED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'COMPLETED' AND DATALENGTH([State]) = DATALENGTH(N'COMPLETED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'CANCELLED' AND DATALENGTH([State]) = DATALENGTH(N'CANCELLED')))");
                        });
                });

            modelBuilder.Entity("UnicoreCRM.Sales.Orders.Domain.OrderReadAuditRecord", b =>
                {
                    b.Property<string>("AuditId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("RecordId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("ResourceVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AuditId");

                    b.HasIndex("WorkspaceId", "OccurredAt");

                    b.ToTable("ReadAuditRecords", "orders", t =>
                        {
                            t.HasCheckConstraint("CK_ReadAuditRecords_Outcome", "(([Outcome] COLLATE Latin1_General_100_BIN2 = N'READ' AND DATALENGTH([Outcome]) = DATALENGTH(N'READ')))");

                            t.HasCheckConstraint("CK_ReadAuditRecords_ResourceVersion", "[ResourceVersion] IS NULL OR [ResourceVersion] >= 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
