// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnicoreCRM.CommercialEvidence.CommercialEvidence.Infrastructure.Persistence;

#nullable disable

namespace UnicoreCRM.CommercialEvidence.CommercialEvidence.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CommercialEvidenceDbContext))]
    partial class CommercialEvidenceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("commercial_evidence")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnicoreCRM.CommercialEvidence.CommercialEvidence.Domain.CommercialEvidenceAuditRecord", b =>
                {
                    b.Property<string>("AuditId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("EvidenceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("AuditId")
                        .HasName("PK_CommercialEvidenceAudit");

                    b.HasIndex("WorkspaceId", "EvidenceId")
                        .IsUnique()
                        .HasDatabaseName("UX_CommercialEvidenceAudit_Workspace_Evidence");

                    b.HasIndex("WorkspaceId", "OccurredAt")
                        .HasDatabaseName("IX_CommercialEvidenceAudit_Workspace_OccurredAt");

                    b.ToTable("AuditRecords", "commercial_evidence", t =>
                        {
                            t.HasCheckConstraint("CK_CommercialEvidenceAudit_Operation", "(([Operation] COLLATE Latin1_General_100_BIN2 = N'ORIGINAL_APPEND' AND DATALENGTH([Operation]) = DATALENGTH(N'ORIGINAL_APPEND')))");
                        });
                });

            modelBuilder.Entity("UnicoreCRM.CommercialEvidence.CommercialEvidence.Domain.PurchaseEvidence", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("EvidenceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("BuyerRefId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("BuyerRefType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("PolicyVersion")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SourceSystem")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.HasKey("WorkspaceId", "EvidenceId")
                        .HasName("PK_PurchaseEvidence");

                    b.HasIndex("WorkspaceId", "SourceType", "SourceSystem", "SourceId")
                        .IsUnique()
                        .HasDatabaseName("UX_PurchaseEvidence_Workspace_Source");

                    b.ToTable("PurchaseEvidence", "commercial_evidence", t =>
                        {
                            t.HasCheckConstraint("CK_PurchaseEvidence_BuyerRefType", "(([BuyerRefType] COLLATE Latin1_General_100_BIN2 = N'CONTACT' AND DATALENGTH([BuyerRefType]) = DATALENGTH(N'CONTACT')) OR ([BuyerRefType] COLLATE Latin1_General_100_BIN2 = N'ORGANIZATION_ACCOUNT' AND DATALENGTH([BuyerRefType]) = DATALENGTH(N'ORGANIZATION_ACCOUNT')))");

                            t.HasCheckConstraint("CK_PurchaseEvidence_CorrelationId", "DATALENGTH([CorrelationId]) > 0");

                            t.HasCheckConstraint("CK_PurchaseEvidence_EvidenceType", "(([EvidenceType] COLLATE Latin1_General_100_BIN2 = N'ORDER_COMPLETED' AND DATALENGTH([EvidenceType]) = DATALENGTH(N'ORDER_COMPLETED')) OR ([EvidenceType] COLLATE Latin1_General_100_BIN2 = N'EXTERNAL_PURCHASE_CONFIRMED' AND DATALENGTH([EvidenceType]) = DATALENGTH(N'EXTERNAL_PURCHASE_CONFIRMED')) OR ([EvidenceType] COLLATE Latin1_General_100_BIN2 = N'HISTORICAL_PURCHASE_IMPORTED' AND DATALENGTH([EvidenceType]) = DATALENGTH(N'HISTORICAL_PURCHASE_IMPORTED')))");

                            t.HasCheckConstraint("CK_PurchaseEvidence_PolicyVersion", "DATALENGTH([PolicyVersion]) > 0");

                            t.HasCheckConstraint("CK_PurchaseEvidence_SourceId", "DATALENGTH([SourceId]) > 0");

                            t.HasCheckConstraint("CK_PurchaseEvidence_SourceMapping", "(([SourceType] = N'ORDER' AND [EvidenceType] = N'ORDER_COMPLETED' AND [SourceSystem] IS NULL) OR ([SourceType] = N'EXTERNAL_PURCHASE' AND [EvidenceType] = N'EXTERNAL_PURCHASE_CONFIRMED' AND [SourceSystem] IS NOT NULL AND DATALENGTH([SourceSystem]) > 0) OR ([SourceType] = N'HISTORICAL_IMPORT' AND [EvidenceType] = N'HISTORICAL_PURCHASE_IMPORTED' AND [SourceSystem] IS NOT NULL AND DATALENGTH([SourceSystem]) > 0))");

                            t.HasCheckConstraint("CK_PurchaseEvidence_SourceType", "(([SourceType] COLLATE Latin1_General_100_BIN2 = N'ORDER' AND DATALENGTH([SourceType]) = DATALENGTH(N'ORDER')) OR ([SourceType] COLLATE Latin1_General_100_BIN2 = N'EXTERNAL_PURCHASE' AND DATALENGTH([SourceType]) = DATALENGTH(N'EXTERNAL_PURCHASE')) OR ([SourceType] COLLATE Latin1_General_100_BIN2 = N'HISTORICAL_IMPORT' AND DATALENGTH([SourceType]) = DATALENGTH(N'HISTORICAL_IMPORT')))");
                        });
                });

            modelBuilder.Entity("UnicoreCRM.CommercialEvidence.CommercialEvidence.Domain.CommercialEvidenceAuditRecord", b =>
                {
                    b.HasOne("UnicoreCRM.CommercialEvidence.CommercialEvidence.Domain.PurchaseEvidence", null)
                        .WithOne()
                        .HasForeignKey("UnicoreCRM.CommercialEvidence.CommercialEvidence.Domain.CommercialEvidenceAuditRecord", "WorkspaceId", "EvidenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_CommercialEvidenceAudit_PurchaseEvidence");
                });
#pragma warning restore 612, 618
        }
    }
}
