<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>UnicoreCRM.Crm</RootNamespace>
    <AssemblyName>UnicoreCRM.Crm</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" />
    <ProjectReference Include="../UnicoreCRM.BuildingBlocks/UnicoreCRM.BuildingBlocks.csproj" />
    <ProjectReference Include="../UnicoreCRM.Platform/UnicoreCRM.Platform.csproj" />
  </ItemGroup>
</Project>
