// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnicoreCRM.Crm.Contacts.Infrastructure.Persistence;

#nullable disable

namespace UnicoreCRM.Crm.Contacts.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContactsDbContext))]
    [Migration("20260909130144_C6ContactRelationships")]
    partial class C6ContactRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("contacts")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnicoreCRM.Crm.Contacts.Domain.Contact", b =>
                {
                    b.Property<string>("ContactId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NormalizedPersonalEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("NormalizedWorkEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("OwnerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Profile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ContactId");

                    b.HasIndex("WorkspaceId", "NormalizedPersonalEmail");

                    b.HasIndex("WorkspaceId", "NormalizedWorkEmail");

                    b.HasIndex("WorkspaceId", "CreatedAt", "ContactId");

                    b.HasIndex("WorkspaceId", "OwnerId", "CreatedAt", "ContactId");

                    b.ToTable("Contacts", "contacts");
                });

            modelBuilder.Entity("UnicoreCRM.Crm.Contacts.Domain.ContactAuditRecord", b =>
                {
                    b.Property<string>("AuditId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AuditId");

                    b.HasIndex("AggregateId", "OccurredAt");

                    b.HasIndex("WorkspaceId", "OccurredAt");

                    b.ToTable("AuditRecords", "contacts");
                });

            modelBuilder.Entity("UnicoreCRM.Crm.Contacts.Domain.ContactConversionRecord", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ConversionKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ResultJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ScopeKey");

                    b.HasIndex("WorkspaceId", "CreatedAt");

                    b.ToTable("ConversionRecords", "contacts");
                });

            modelBuilder.Entity("UnicoreCRM.Crm.Contacts.Domain.ContactCustomerRelationship", b =>
                {
                    b.Property<string>("RelationshipId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("EndedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("RelationshipId");

                    b.HasIndex("WorkspaceId", "CustomerId")
                        .IsUnique()
                        .HasFilter("[EffectiveTo] IS NULL AND [Role] = N'primary_contact'");

                    b.HasIndex("WorkspaceId", "ContactId", "CustomerId")
                        .IsUnique()
                        .HasFilter("[EffectiveTo] IS NULL");

                    b.HasIndex("WorkspaceId", "CustomerId", "EffectiveTo");

                    b.HasIndex("WorkspaceId", "ContactId", "EffectiveTo", "EffectiveFrom", "RelationshipId");

                    b.ToTable("CustomerRelationships", "contacts", t =>
                        {
                            t.HasCheckConstraint("CK_CustomerRelationships_DateRange", "[EffectiveTo] IS NULL OR [EffectiveTo] >= [EffectiveFrom]");

                            t.HasCheckConstraint("CK_CustomerRelationships_EndState", "([EffectiveTo] IS NULL AND [EndedReason] IS NULL) OR ([EffectiveTo] IS NOT NULL AND LEN(LTRIM(RTRIM([EndedReason]))) > 0)");

                            t.HasCheckConstraint("CK_CustomerRelationships_Role", "[Role] COLLATE Latin1_General_100_BIN2 IN (N'primary_contact',N'billing',N'decision_maker',N'end_user',N'technical',N'support',N'other')");
                        });
                });

            modelBuilder.Entity("UnicoreCRM.Crm.Contacts.Domain.ContactIdempotencyRecord", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ScopeKey");

                    b.HasIndex("WorkspaceId", "CreatedAt");

                    b.ToTable("IdempotencyRecords", "contacts");
                });

            modelBuilder.Entity("UnicoreCRM.Crm.Contacts.Domain.ContactOrganizationRelationship", b =>
                {
                    b.Property<string>("RelationshipId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContactId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("EffectiveTo")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("EndedReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsPrimaryAffiliation")
                        .HasColumnType("bit");

                    b.Property<string>("LegacyEvidenceJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("RelationshipId");

                    b.HasIndex("WorkspaceId", "ContactId")
                        .IsUnique()
                        .HasFilter("[EffectiveTo] IS NULL AND [IsPrimaryAffiliation] = 1");

                    b.HasIndex("WorkspaceId", "ContactId", "OrganizationId")
                        .IsUnique()
                        .HasFilter("[EffectiveTo] IS NULL");

                    b.HasIndex("WorkspaceId", "OrganizationId", "EffectiveTo");

                    b.HasIndex("WorkspaceId", "ContactId", "EffectiveTo", "EffectiveFrom", "RelationshipId");

                    b.ToTable("OrganizationRelationships", "contacts", t =>
                        {
                            t.HasCheckConstraint("CK_OrganizationRelationships_DateRange", "[EffectiveTo] IS NULL OR [EffectiveTo] >= [EffectiveFrom]");

                            t.HasCheckConstraint("CK_OrganizationRelationships_EndState", "([EffectiveTo] IS NULL AND [EndedReason] IS NULL) OR ([EffectiveTo] IS NOT NULL AND LEN(LTRIM(RTRIM([EndedReason]))) > 0)");

                            t.HasCheckConstraint("CK_OrganizationRelationships_Role", "[Role] COLLATE Latin1_General_100_BIN2 IN (N'employee',N'executive',N'decision_maker',N'buyer',N'finance',N'technical',N'advisor',N'partner',N'other')");
                        });
                });

            modelBuilder.Entity("UnicoreCRM.Crm.Contacts.Domain.ContactOutboxMessage", b =>
                {
                    b.Property<string>("EventId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("EventId");

                    b.HasIndex("WorkspaceId", "OccurredAt");

                    b.ToTable("OutboxMessages", "contacts");
                });

            modelBuilder.Entity("UnicoreCRM.Crm.Contacts.Domain.ContactReadAuditRecord", b =>
                {
                    b.Property<string>("AuditId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ContactId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("ContactVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AuditId");

                    b.HasIndex("ContactId", "OccurredAt");

                    b.HasIndex("WorkspaceId", "OccurredAt");

                    b.ToTable("ReadAuditRecords", "contacts");
                });

            modelBuilder.Entity("UnicoreCRM.Crm.Contacts.Domain.ContactCustomerRelationship", b =>
                {
                    b.HasOne("UnicoreCRM.Crm.Contacts.Domain.Contact", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ContactId")
                        .HasPrincipalKey("WorkspaceId", "ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("UnicoreCRM.Crm.Contacts.Domain.ContactOrganizationRelationship", b =>
                {
                    b.HasOne("UnicoreCRM.Crm.Contacts.Domain.Contact", null)
                        .WithMany()
                        .HasForeignKey("WorkspaceId", "ContactId")
                        .HasPrincipalKey("WorkspaceId", "ContactId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
