// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnicoreCRM.Workflows.Atomic.Infrastructure.Persistence;

#nullable disable

namespace UnicoreCRM.Workflows.Atomic.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorkflowsDbContext))]
    [Migration("20260912112701_HardenLeadCustomerConversion")]
    partial class HardenLeadCustomerConversion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workflow")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnicoreCRM.Workflows.Atomic.Domain.LeadCustomerConversionAnchor", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("int");

                    b.Property<string>("AuditEvidenceIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BusinessIntentFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ConversionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ConversionType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("CustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CustomerResolution")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long?>("CustomerVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("EmittedEventIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExecutionAttemptId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ExecutionLeaseAcquiredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("ExecutionLeaseExpiresAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("ExecutionPrincipalId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("ExpectedLeadVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("FrozenLeadOwnerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LastErrorCategory")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("LastErrorCode")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LeadId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("LeadVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OriginalAccountId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OriginalMemberId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OriginalMembershipId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("OriginalPrincipalId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SubjectType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("SubjectVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ScopeKey");

                    b.HasIndex("ConversionId")
                        .IsUnique();

                    b.HasIndex("Stage", "NextRetryAt", "UpdatedAt");

                    b.HasIndex("WorkspaceId", "LeadId", "ConversionType")
                        .IsUnique();

                    b.ToTable("LeadCustomerConversionAnchors", "workflow");
                });

            modelBuilder.Entity("UnicoreCRM.Workflows.Atomic.Domain.LeadQualificationAnchor", b =>
                {
                    b.Property<string>("ScopeKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ContactDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ContactId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("ContactVersion")
                        .HasColumnType("bigint");

                    b.Property<bool?>("ContactWasCreated")
                        .HasColumnType("bit");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DealId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("DealVersion")
                        .HasColumnType("bigint");

                    b.Property<long>("ExpectedLeadVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("IntentVersion")
                        .HasColumnType("int");

                    b.Property<string>("LeadId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("LeadVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("ParticipantMemberId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TaskAssigneeId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("TaskId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("TaskVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Workflow")
                        .IsRequired()
                        .HasMaxLength(96)
                        .HasColumnType("nvarchar(96)");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("ScopeKey");

                    b.HasIndex("Stage", "UpdatedAt");

                    b.HasIndex("WorkspaceId", "LeadId");

                    b.ToTable("LeadQualificationAnchors", "workflow");
                });
#pragma warning restore 612, 618
        }
    }
}
