// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UnicoreCRM.Billing.Payments.Infrastructure.Persistence;

#nullable disable

namespace UnicoreCRM.Billing.Payments.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PaymentsDbContext))]
    partial class PaymentsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("payments")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UnicoreCRM.Billing.Payments.Domain.PaymentIntent", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BuyerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CheckoutUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("FailureCode")
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("InvoiceIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MethodCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrderId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Purpose")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<long>("ResourceVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("ScheduleLineIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("WorkspaceId", "PaymentIntentId");

                    b.HasIndex("WorkspaceId", "OrderId");

                    b.ToTable("PaymentIntents", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentIntents_BuyerType", "(([BuyerType] COLLATE Latin1_General_100_BIN2 = N'CONTACT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'CONTACT')) OR ([BuyerType] COLLATE Latin1_General_100_BIN2 = N'ORGANIZATION_ACCOUNT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'ORGANIZATION_ACCOUNT')))");

                            t.HasCheckConstraint("CK_PaymentIntents_Currency", "[Currency] LIKE '[A-Z][A-Z][A-Z]' COLLATE Latin1_General_100_BIN2 AND DATALENGTH([Currency]) = 6");

                            t.HasCheckConstraint("CK_PaymentIntents_InvoiceIdsJson", "ISJSON([InvoiceIdsJson]) = 1");

                            t.HasCheckConstraint("CK_PaymentIntents_Purpose", "[Purpose] IS NULL OR ((([Purpose] COLLATE Latin1_General_100_BIN2 = N'DEPOSIT' AND DATALENGTH([Purpose]) = DATALENGTH(N'DEPOSIT')) OR ([Purpose] COLLATE Latin1_General_100_BIN2 = N'FULL_PAYMENT' AND DATALENGTH([Purpose]) = DATALENGTH(N'FULL_PAYMENT')) OR ([Purpose] COLLATE Latin1_General_100_BIN2 = N'INSTALLMENT' AND DATALENGTH([Purpose]) = DATALENGTH(N'INSTALLMENT')) OR ([Purpose] COLLATE Latin1_General_100_BIN2 = N'OVERDUE_REMINDER' AND DATALENGTH([Purpose]) = DATALENGTH(N'OVERDUE_REMINDER')) OR ([Purpose] COLLATE Latin1_General_100_BIN2 = N'OTHER' AND DATALENGTH([Purpose]) = DATALENGTH(N'OTHER'))))");

                            t.HasCheckConstraint("CK_PaymentIntents_ResourceVersion", "[ResourceVersion] >= 0");

                            t.HasCheckConstraint("CK_PaymentIntents_ScheduleLineIdsJson", "ISJSON([ScheduleLineIdsJson]) = 1");

                            t.HasCheckConstraint("CK_PaymentIntents_State", "(([State] COLLATE Latin1_General_100_BIN2 = N'CREATED' AND DATALENGTH([State]) = DATALENGTH(N'CREATED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'REQUIRES_ACTION' AND DATALENGTH([State]) = DATALENGTH(N'REQUIRES_ACTION')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'PROCESSING' AND DATALENGTH([State]) = DATALENGTH(N'PROCESSING')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'SUCCEEDED' AND DATALENGTH([State]) = DATALENGTH(N'SUCCEEDED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'FAILED' AND DATALENGTH([State]) = DATALENGTH(N'FAILED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'CANCELLED' AND DATALENGTH([State]) = DATALENGTH(N'CANCELLED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'EXPIRED' AND DATALENGTH([State]) = DATALENGTH(N'EXPIRED')))");
                        });
                });

            modelBuilder.Entity("UnicoreCRM.Billing.Payments.Domain.PaymentPlan", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PaymentPlanId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("AgreementSnapshotJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BuyerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<int>("EvidenceCount")
                        .HasColumnType("int");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("ResourceVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("ScheduleLineIdsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("SupersededByPlanId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SupersedesPlanId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("WorkspaceId", "PaymentPlanId");

                    b.HasIndex("WorkspaceId", "OrderId");

                    b.ToTable("PaymentPlans", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentPlans_AgreementSnapshotJson", "ISJSON([AgreementSnapshotJson]) = 1");

                            t.HasCheckConstraint("CK_PaymentPlans_BuyerType", "(([BuyerType] COLLATE Latin1_General_100_BIN2 = N'CONTACT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'CONTACT')) OR ([BuyerType] COLLATE Latin1_General_100_BIN2 = N'ORGANIZATION_ACCOUNT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'ORGANIZATION_ACCOUNT')))");

                            t.HasCheckConstraint("CK_PaymentPlans_Currency", "[Currency] LIKE '[A-Z][A-Z][A-Z]' COLLATE Latin1_General_100_BIN2 AND DATALENGTH([Currency]) = 6");

                            t.HasCheckConstraint("CK_PaymentPlans_EvidenceCount", "[EvidenceCount] >= 0");

                            t.HasCheckConstraint("CK_PaymentPlans_Kind", "(([Kind] COLLATE Latin1_General_100_BIN2 = N'FULL_PAYMENT' AND DATALENGTH([Kind]) = DATALENGTH(N'FULL_PAYMENT')) OR ([Kind] COLLATE Latin1_General_100_BIN2 = N'DEPOSIT_AND_BALANCE' AND DATALENGTH([Kind]) = DATALENGTH(N'DEPOSIT_AND_BALANCE')) OR ([Kind] COLLATE Latin1_General_100_BIN2 = N'INSTALLMENT' AND DATALENGTH([Kind]) = DATALENGTH(N'INSTALLMENT')) OR ([Kind] COLLATE Latin1_General_100_BIN2 = N'MILESTONE' AND DATALENGTH([Kind]) = DATALENGTH(N'MILESTONE')) OR ([Kind] COLLATE Latin1_General_100_BIN2 = N'CUSTOM' AND DATALENGTH([Kind]) = DATALENGTH(N'CUSTOM')))");

                            t.HasCheckConstraint("CK_PaymentPlans_ResourceVersion", "[ResourceVersion] >= 0");

                            t.HasCheckConstraint("CK_PaymentPlans_ScheduleLineIdsJson", "ISJSON([ScheduleLineIdsJson]) = 1");

                            t.HasCheckConstraint("CK_PaymentPlans_State", "(([State] COLLATE Latin1_General_100_BIN2 = N'DRAFT' AND DATALENGTH([State]) = DATALENGTH(N'DRAFT')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'ACTIVE' AND DATALENGTH([State]) = DATALENGTH(N'ACTIVE')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'SUPERSEDED' AND DATALENGTH([State]) = DATALENGTH(N'SUPERSEDED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'CANCELLED' AND DATALENGTH([State]) = DATALENGTH(N'CANCELLED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'COMPLETED' AND DATALENGTH([State]) = DATALENGTH(N'COMPLETED')))");
                        });
                });

            modelBuilder.Entity("UnicoreCRM.Billing.Payments.Domain.PaymentReadAuditRecord", b =>
                {
                    b.Property<string>("AuditId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("RecordId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long?>("ResourceVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("WorkspaceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("AuditId");

                    b.HasIndex("WorkspaceId", "OccurredAt");

                    b.ToTable("ReadAuditRecords", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_ReadAuditRecords_Outcome", "(([Outcome] COLLATE Latin1_General_100_BIN2 = N'READ' AND DATALENGTH([Outcome]) = DATALENGTH(N'READ')))");

                            t.HasCheckConstraint("CK_ReadAuditRecords_ResourceVersion", "[ResourceVersion] IS NULL OR [ResourceVersion] >= 0");
                        });
                });

            modelBuilder.Entity("UnicoreCRM.Billing.Payments.Domain.PaymentRecord", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PaymentRecordId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AllocationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BuyerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CodCustomerCollectionState")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("CodMerchantRemittanceState")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("CustomerCreditsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EffectiveForReceivables")
                        .HasColumnType("bit");

                    b.Property<string>("EvidenceJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExternalReference")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("MethodCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("OrderId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PaymentIntentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReconciliationState")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("RefundIntentId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RefundOfCustomerCreditId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("RefundOfPaymentRecordId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("RefundableAmount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("RefundableCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("RefundsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ResourceVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<decimal>("UnallocatedAmount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("UnallocatedCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("WorkspaceId", "PaymentRecordId");

                    b.HasIndex("WorkspaceId", "BuyerId");

                    b.ToTable("PaymentRecords", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentRecords_AllocationsJson", "ISJSON([AllocationsJson]) = 1");

                            t.HasCheckConstraint("CK_PaymentRecords_BuyerType", "(([BuyerType] COLLATE Latin1_General_100_BIN2 = N'CONTACT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'CONTACT')) OR ([BuyerType] COLLATE Latin1_General_100_BIN2 = N'ORGANIZATION_ACCOUNT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'ORGANIZATION_ACCOUNT')))");

                            t.HasCheckConstraint("CK_PaymentRecords_Channel", "(([Channel] COLLATE Latin1_General_100_BIN2 = N'BANK' AND DATALENGTH([Channel]) = DATALENGTH(N'BANK')) OR ([Channel] COLLATE Latin1_General_100_BIN2 = N'ONLINE_GATEWAY' AND DATALENGTH([Channel]) = DATALENGTH(N'ONLINE_GATEWAY')) OR ([Channel] COLLATE Latin1_General_100_BIN2 = N'POS' AND DATALENGTH([Channel]) = DATALENGTH(N'POS')) OR ([Channel] COLLATE Latin1_General_100_BIN2 = N'CARRIER' AND DATALENGTH([Channel]) = DATALENGTH(N'CARRIER')) OR ([Channel] COLLATE Latin1_General_100_BIN2 = N'OFFLINE' AND DATALENGTH([Channel]) = DATALENGTH(N'OFFLINE')) OR ([Channel] COLLATE Latin1_General_100_BIN2 = N'EXTERNAL' AND DATALENGTH([Channel]) = DATALENGTH(N'EXTERNAL')))");

                            t.HasCheckConstraint("CK_PaymentRecords_CodCustomerCollectionState", "[CodCustomerCollectionState] IS NULL OR ((([CodCustomerCollectionState] COLLATE Latin1_General_100_BIN2 = N'NOT_REQUESTED' AND DATALENGTH([CodCustomerCollectionState]) = DATALENGTH(N'NOT_REQUESTED')) OR ([CodCustomerCollectionState] COLLATE Latin1_General_100_BIN2 = N'REQUESTED' AND DATALENGTH([CodCustomerCollectionState]) = DATALENGTH(N'REQUESTED')) OR ([CodCustomerCollectionState] COLLATE Latin1_General_100_BIN2 = N'COLLECTED' AND DATALENGTH([CodCustomerCollectionState]) = DATALENGTH(N'COLLECTED')) OR ([CodCustomerCollectionState] COLLATE Latin1_General_100_BIN2 = N'FAILED' AND DATALENGTH([CodCustomerCollectionState]) = DATALENGTH(N'FAILED'))))");

                            t.HasCheckConstraint("CK_PaymentRecords_CodMerchantRemittanceState", "[CodMerchantRemittanceState] IS NULL OR ((([CodMerchantRemittanceState] COLLATE Latin1_General_100_BIN2 = N'NOT_APPLICABLE' AND DATALENGTH([CodMerchantRemittanceState]) = DATALENGTH(N'NOT_APPLICABLE')) OR ([CodMerchantRemittanceState] COLLATE Latin1_General_100_BIN2 = N'PENDING' AND DATALENGTH([CodMerchantRemittanceState]) = DATALENGTH(N'PENDING')) OR ([CodMerchantRemittanceState] COLLATE Latin1_General_100_BIN2 = N'REMITTED' AND DATALENGTH([CodMerchantRemittanceState]) = DATALENGTH(N'REMITTED')) OR ([CodMerchantRemittanceState] COLLATE Latin1_General_100_BIN2 = N'FAILED' AND DATALENGTH([CodMerchantRemittanceState]) = DATALENGTH(N'FAILED'))))");

                            t.HasCheckConstraint("CK_PaymentRecords_Currency", "[Currency] LIKE '[A-Z][A-Z][A-Z]' COLLATE Latin1_General_100_BIN2 AND DATALENGTH([Currency]) = 6");

                            t.HasCheckConstraint("CK_PaymentRecords_CustomerCreditsJson", "ISJSON([CustomerCreditsJson]) = 1");

                            t.HasCheckConstraint("CK_PaymentRecords_EvidenceJson", "[EvidenceJson] IS NULL OR ISJSON([EvidenceJson]) = 1");

                            t.HasCheckConstraint("CK_PaymentRecords_Kind", "(([Kind] COLLATE Latin1_General_100_BIN2 = N'PAYMENT' AND DATALENGTH([Kind]) = DATALENGTH(N'PAYMENT')) OR ([Kind] COLLATE Latin1_General_100_BIN2 = N'REFUND' AND DATALENGTH([Kind]) = DATALENGTH(N'REFUND')))");

                            t.HasCheckConstraint("CK_PaymentRecords_ReconciliationState", "(([ReconciliationState] COLLATE Latin1_General_100_BIN2 = N'UNRECONCILED' AND DATALENGTH([ReconciliationState]) = DATALENGTH(N'UNRECONCILED')) OR ([ReconciliationState] COLLATE Latin1_General_100_BIN2 = N'MATCHED' AND DATALENGTH([ReconciliationState]) = DATALENGTH(N'MATCHED')) OR ([ReconciliationState] COLLATE Latin1_General_100_BIN2 = N'MISMATCH' AND DATALENGTH([ReconciliationState]) = DATALENGTH(N'MISMATCH')))");

                            t.HasCheckConstraint("CK_PaymentRecords_RefundableCurrency", "[RefundableCurrency] LIKE '[A-Z][A-Z][A-Z]' COLLATE Latin1_General_100_BIN2 AND DATALENGTH([RefundableCurrency]) = 6");

                            t.HasCheckConstraint("CK_PaymentRecords_RefundsJson", "ISJSON([RefundsJson]) = 1");

                            t.HasCheckConstraint("CK_PaymentRecords_ResourceVersion", "[ResourceVersion] >= 0");

                            t.HasCheckConstraint("CK_PaymentRecords_State", "(([State] COLLATE Latin1_General_100_BIN2 = N'CREATED' AND DATALENGTH([State]) = DATALENGTH(N'CREATED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'PENDING' AND DATALENGTH([State]) = DATALENGTH(N'PENDING')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'PROCESSING' AND DATALENGTH([State]) = DATALENGTH(N'PROCESSING')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'SUCCEEDED' AND DATALENGTH([State]) = DATALENGTH(N'SUCCEEDED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'FAILED' AND DATALENGTH([State]) = DATALENGTH(N'FAILED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'CANCELLED' AND DATALENGTH([State]) = DATALENGTH(N'CANCELLED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'EXPIRED' AND DATALENGTH([State]) = DATALENGTH(N'EXPIRED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'REVERSED' AND DATALENGTH([State]) = DATALENGTH(N'REVERSED')))");

                            t.HasCheckConstraint("CK_PaymentRecords_UnallocatedCurrency", "[UnallocatedCurrency] LIKE '[A-Z][A-Z][A-Z]' COLLATE Latin1_General_100_BIN2 AND DATALENGTH([UnallocatedCurrency]) = 6");
                        });
                });

            modelBuilder.Entity("UnicoreCRM.Billing.Payments.Domain.PaymentScheduleLine", b =>
                {
                    b.Property<string>("WorkspaceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("PaymentScheduleLineId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("AllowedMethodCodesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("AmountCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("AmountRuleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BuyerType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Channel")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DueRuleJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FulfillmentGate")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("InvoicePolicyCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("OutstandingAmount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("OutstandingCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<string>("PaymentPlanId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<long>("PaymentPlanVersion")
                        .HasColumnType("bigint");

                    b.Property<string>("PreferredMethodCode")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateOnly?>("ResolvedDueDate")
                        .HasColumnType("date");

                    b.Property<long>("ResourceVersion")
                        .HasColumnType("bigint");

                    b.Property<decimal>("SatisfiedAmount")
                        .HasPrecision(38, 6)
                        .HasColumnType("decimal(38,6)");

                    b.Property<string>("SatisfiedCurrency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasPrecision(7)
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("WorkspaceId", "PaymentScheduleLineId");

                    b.HasIndex("WorkspaceId", "PaymentPlanId");

                    b.ToTable("PaymentScheduleLines", "payments", t =>
                        {
                            t.HasCheckConstraint("CK_PaymentScheduleLines_AllowedMethodCodesJson", "ISJSON([AllowedMethodCodesJson]) = 1");

                            t.HasCheckConstraint("CK_PaymentScheduleLines_AmountRuleJson", "ISJSON([AmountRuleJson]) = 1");

                            t.HasCheckConstraint("CK_PaymentScheduleLines_BuyerType", "(([BuyerType] COLLATE Latin1_General_100_BIN2 = N'CONTACT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'CONTACT')) OR ([BuyerType] COLLATE Latin1_General_100_BIN2 = N'ORGANIZATION_ACCOUNT' AND DATALENGTH([BuyerType]) = DATALENGTH(N'ORGANIZATION_ACCOUNT')))");

                            t.HasCheckConstraint("CK_PaymentScheduleLines_Channel", "[Channel] IS NULL OR ((([Channel] COLLATE Latin1_General_100_BIN2 = N'BANK' AND DATALENGTH([Channel]) = DATALENGTH(N'BANK')) OR ([Channel] COLLATE Latin1_General_100_BIN2 = N'ONLINE_GATEWAY' AND DATALENGTH([Channel]) = DATALENGTH(N'ONLINE_GATEWAY')) OR ([Channel] COLLATE Latin1_General_100_BIN2 = N'POS' AND DATALENGTH([Channel]) = DATALENGTH(N'POS')) OR ([Channel] COLLATE Latin1_General_100_BIN2 = N'CARRIER' AND DATALENGTH([Channel]) = DATALENGTH(N'CARRIER')) OR ([Channel] COLLATE Latin1_General_100_BIN2 = N'OFFLINE' AND DATALENGTH([Channel]) = DATALENGTH(N'OFFLINE')) OR ([Channel] COLLATE Latin1_General_100_BIN2 = N'EXTERNAL' AND DATALENGTH([Channel]) = DATALENGTH(N'EXTERNAL'))))");

                            t.HasCheckConstraint("CK_PaymentScheduleLines_DueRuleJson", "ISJSON([DueRuleJson]) = 1");

                            t.HasCheckConstraint("CK_PaymentScheduleLines_FulfillmentGate", "(([FulfillmentGate] COLLATE Latin1_General_100_BIN2 = N'NONE' AND DATALENGTH([FulfillmentGate]) = DATALENGTH(N'NONE')) OR ([FulfillmentGate] COLLATE Latin1_General_100_BIN2 = N'BEFORE_BOOKING' AND DATALENGTH([FulfillmentGate]) = DATALENGTH(N'BEFORE_BOOKING')) OR ([FulfillmentGate] COLLATE Latin1_General_100_BIN2 = N'BEFORE_DISPATCH' AND DATALENGTH([FulfillmentGate]) = DATALENGTH(N'BEFORE_DISPATCH')) OR ([FulfillmentGate] COLLATE Latin1_General_100_BIN2 = N'BEFORE_COMPLETION' AND DATALENGTH([FulfillmentGate]) = DATALENGTH(N'BEFORE_COMPLETION')))");

                            t.HasCheckConstraint("CK_PaymentScheduleLines_PlanVersion", "[PaymentPlanVersion] >= 0");

                            t.HasCheckConstraint("CK_PaymentScheduleLines_Purpose", "(([Purpose] COLLATE Latin1_General_100_BIN2 = N'FULL' AND DATALENGTH([Purpose]) = DATALENGTH(N'FULL')) OR ([Purpose] COLLATE Latin1_General_100_BIN2 = N'DEPOSIT' AND DATALENGTH([Purpose]) = DATALENGTH(N'DEPOSIT')) OR ([Purpose] COLLATE Latin1_General_100_BIN2 = N'BALANCE' AND DATALENGTH([Purpose]) = DATALENGTH(N'BALANCE')) OR ([Purpose] COLLATE Latin1_General_100_BIN2 = N'INSTALLMENT' AND DATALENGTH([Purpose]) = DATALENGTH(N'INSTALLMENT')) OR ([Purpose] COLLATE Latin1_General_100_BIN2 = N'MILESTONE' AND DATALENGTH([Purpose]) = DATALENGTH(N'MILESTONE')) OR ([Purpose] COLLATE Latin1_General_100_BIN2 = N'OTHER' AND DATALENGTH([Purpose]) = DATALENGTH(N'OTHER')))");

                            t.HasCheckConstraint("CK_PaymentScheduleLines_ResourceVersion", "[ResourceVersion] >= 0");

                            t.HasCheckConstraint("CK_PaymentScheduleLines_Sequence", "[Sequence] >= 1");

                            t.HasCheckConstraint("CK_PaymentScheduleLines_State", "(([State] COLLATE Latin1_General_100_BIN2 = N'SCHEDULED' AND DATALENGTH([State]) = DATALENGTH(N'SCHEDULED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'NOT_DUE' AND DATALENGTH([State]) = DATALENGTH(N'NOT_DUE')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'DUE' AND DATALENGTH([State]) = DATALENGTH(N'DUE')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'PARTIAL' AND DATALENGTH([State]) = DATALENGTH(N'PARTIAL')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'SATISFIED' AND DATALENGTH([State]) = DATALENGTH(N'SATISFIED')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'OVERDUE' AND DATALENGTH([State]) = DATALENGTH(N'OVERDUE')) OR ([State] COLLATE Latin1_General_100_BIN2 = N'VOIDED' AND DATALENGTH([State]) = DATALENGTH(N'VOIDED')))");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
