using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.EntityFrameworkCore;
using UnicoreCRM.BuildingBlocks;
using UnicoreCRM.Integrations.Infrastructure.Persistence;
using UnicoreCRM.Integrations.Webhooks.Outbound.Contracts;
using UnicoreCRM.Integrations.Webhooks.Outbound.Domain;
using UnicoreCRM.Integrations.Webhooks.Outbound.Infrastructure;
using UnicoreCRM.Platform.AccessControl.Contracts;
namespace UnicoreCRM.Integrations.Webhooks.Outbound.Application;

internal sealed record WebhookCommandContext(string IdempotencyKey, long? ExpectedVersion, string CorrelationId);
internal sealed record WebhookResult<T>(bool IsSuccess, T? Value = null, string? Code = null, int Status = 200) where T : class;
internal sealed class OutboundWebhookService(IntegrationsDbContext db, IAccessAuthorizer access, IDataProtectionProvider protection, IWebhookHostResolver resolver, IIntegrationEventCatalog catalog, TimeProvider clock)
{
    private static readonly AccessRequirement Read = AccessRequirement.ForCanonicalCapability("studio.read"); private static readonly AccessRequirement Configure = AccessRequirement.ForCanonicalCapability("studio.configure"); private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);
    internal async Task<WebhookResult<IReadOnlyList<IntegrationEventCatalogItem>>> Catalog(string correlation, CancellationToken ct) { var a = await Authorize(Read, correlation, ct); return a is null ? new(false, Code: "ACCESS_DENIED", Status: 403) : new(true, catalog.Events.Select(x => new IntegrationEventCatalogItem(x.EventType,x.SchemaVersion,x.Name,x.Description,x.SourceCategory)).ToArray()); }
    internal async Task<WebhookResult<IReadOnlyList<OutboundWebhookSubscriptionDocument>>> List(string correlation, CancellationToken ct) { var a = await Authorize(Read, correlation, ct); if (a is null) return new(false, Code: "ACCESS_DENIED", Status: 403); var rows = await db.OutboundWebhookSubscriptions.AsNoTracking().Where(x => x.WorkspaceId == a.WorkspaceId).OrderBy(x => x.Name).ToArrayAsync(ct); return new(true, rows.Select(Project).ToArray()); }
    internal async Task<WebhookResult<OutboundWebhookSubscriptionDocument>> Get(string id, string correlation, CancellationToken ct) { var a = await Authorize(Read, correlation, ct); if (a is null) return new(false, Code: "ACCESS_DENIED", Status: 403); var row = await db.OutboundWebhookSubscriptions.AsNoTracking().SingleOrDefaultAsync(x => x.WorkspaceId == a.WorkspaceId && x.SubscriptionId == id, ct); return row is null ? new(false, Code: "RESOURCE_NOT_FOUND", Status: 404) : new(true, Project(row)); }
    internal async Task<WebhookResult<OutboundWebhookMutationResponse>> Create(CreateOutboundWebhookSubscriptionRequest request, WebhookCommandContext command, CancellationToken ct) { var a = await Authorize(Configure, command.CorrelationId, ct); if (a is null) return new(false, Code: "ACCESS_DENIED", Status: 403); var validation = await Validate(request.Name, request.EventType, request.EndpointUrl, ct); if (validation is not null) return new(false, Code: validation, Status: 422); var fingerprint = Fingerprint(request); var replay = await Replay<OutboundWebhookMutationResponse>(a.WorkspaceId, "create", command.IdempotencyKey, fingerprint, ct); if (replay is not null) return replay; var secret = Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)); var protectedSecret = protection.CreateProtector("UnicoreCRM.Integrations.Webhooks.Outbound.SigningSecret.v1").Protect(secret); var row = new OutboundWebhookSubscription(a.WorkspaceId, request.Name.Trim(), request.EventType, request.EndpointUrl, protectedSecret, a.MemberId, clock.GetUtcNow()); db.OutboundWebhookSubscriptions.Add(row); var response = new OutboundWebhookMutationResponse(Project(row), "COMMITTED", secret); Record(a, "create", row.SubscriptionId, command, fingerprint, response with { SigningSecret = null }); await db.SaveChangesAsync(ct); return new(true, response, Status: 201); }
    internal Task<WebhookResult<OutboundWebhookMutationResponse>> Update(string id, UpdateOutboundWebhookSubscriptionRequest request, WebhookCommandContext command, CancellationToken ct) => Mutate(id, "update", command, ct, async (row, a) => { var invalid = await Validate(request.Name, request.EventType, request.EndpointUrl, ct); if (invalid is not null) throw new WebhookRuleException(invalid, 422); row.Update(request.Name.Trim(), request.EventType, request.EndpointUrl, a.MemberId, clock.GetUtcNow()); }, request);
    internal Task<WebhookResult<OutboundWebhookMutationResponse>> Activate(string id, WebhookCommandContext c, CancellationToken ct) => Mutate(id, "activate", c, ct, (x, a) => { x.Activate(a.MemberId, clock.GetUtcNow()); return Task.CompletedTask; }, new { });
    internal Task<WebhookResult<OutboundWebhookMutationResponse>> Pause(string id, WebhookCommandContext c, CancellationToken ct) => Mutate(id, "pause", c, ct, (x, a) => { x.Pause(a.MemberId, clock.GetUtcNow()); return Task.CompletedTask; }, new { });
    internal Task<WebhookResult<OutboundWebhookMutationResponse>> Resume(string id, WebhookCommandContext c, CancellationToken ct) => Mutate(id, "resume", c, ct, (x, a) => { x.Resume(a.MemberId, clock.GetUtcNow()); return Task.CompletedTask; }, new { });
    internal Task<WebhookResult<OutboundWebhookMutationResponse>> Archive(string id, WebhookCommandContext c, CancellationToken ct) => Mutate(id, "archive", c, ct, (x, a) => { x.Archive(a.MemberId, clock.GetUtcNow()); return Task.CompletedTask; }, new { });
    internal async Task<WebhookResult<OutboundWebhookMutationResponse>> Rotate(string id, WebhookCommandContext c, CancellationToken ct) { string? plain = null; return await Mutate(id, "rotate-secret", c, ct, (x, a) => { plain = Convert.ToBase64String(RandomNumberGenerator.GetBytes(32)); x.Rotate(protection.CreateProtector("UnicoreCRM.Integrations.Webhooks.Outbound.SigningSecret.v1").Protect(plain), a.MemberId, clock.GetUtcNow()); return Task.CompletedTask; }, new { }, () => plain); }
    internal async Task<WebhookResult<IReadOnlyList<OutboundWebhookDeliveryDocument>>> Deliveries(string? subscriptionId, string correlation, CancellationToken ct) { var a = await Authorize(Read, correlation, ct); if (a is null) return new(false, Code: "ACCESS_DENIED", Status: 403); var q = db.OutboundWebhookDeliveries.AsNoTracking().Where(x => x.WorkspaceId == a.WorkspaceId); if (subscriptionId is not null) q = q.Where(x => x.SubscriptionId == subscriptionId); var rows = await q.OrderByDescending(x => x.CreatedAt).Take(200).ToArrayAsync(ct); return new(true, rows.Select(Project).ToArray()); }
    internal async Task<WebhookResult<OutboundWebhookDeliveryDocument>> ReplayDelivery(string id, WebhookCommandContext c, CancellationToken ct) { var a = await Authorize(Configure, c.CorrelationId, ct); if (a is null) return new(false, Code: "ACCESS_DENIED", Status: 403); var fp = Fingerprint(new { id }); var replay = await Replay<OutboundWebhookDeliveryDocument>(a.WorkspaceId, "replay", c.IdempotencyKey, fp, ct); if (replay is not null) return replay; var row = await db.OutboundWebhookDeliveries.SingleOrDefaultAsync(x => x.WorkspaceId == a.WorkspaceId && x.DeliveryId == id, ct); if (row is null) return new(false, Code: "RESOURCE_NOT_FOUND", Status: 404); try { row.Replay(clock.GetUtcNow()); } catch { return new(false, Code: "DELIVERY_NOT_REPLAYABLE", Status: 409); } var response = Project(row); Record(a, "replay", id, c, fp, response); await db.SaveChangesAsync(ct); return new(true, response); }
    private async Task<WebhookResult<OutboundWebhookMutationResponse>> Mutate<T>(string id, string operation, WebhookCommandContext c, CancellationToken ct, Func<OutboundWebhookSubscription, AuthorizationContextDocument, Task> action, T body, Func<string?>? secret = null) { var a = await Authorize(Configure, c.CorrelationId, ct); if (a is null) return new(false, Code: "ACCESS_DENIED", Status: 403); var fp = Fingerprint(new { id, body, expectedVersion = c.ExpectedVersion }); var replay = await Replay<OutboundWebhookMutationResponse>(a.WorkspaceId, operation, c.IdempotencyKey, fp, ct); if (replay is not null) return replay; var row = await db.OutboundWebhookSubscriptions.SingleOrDefaultAsync(x => x.WorkspaceId == a.WorkspaceId && x.SubscriptionId == id, ct); if (row is null) return new(false, Code: "RESOURCE_NOT_FOUND", Status: 404); if (c.ExpectedVersion != row.Version) return new(false, Code: "RESOURCE_VERSION_CONFLICT", Status: 409); try { await action(row, a); } catch (WebhookRuleException e) { return new(false, Code: e.Code, Status: e.Status); } catch (InvalidOperationException) { return new(false, Code: "LIFECYCLE_CONFLICT", Status: 409); } var response = new OutboundWebhookMutationResponse(Project(row), "COMMITTED", secret?.Invoke()); Record(a, operation, id, c, fp, response with { SigningSecret = null }); try { await db.SaveChangesAsync(ct); } catch (DbUpdateConcurrencyException) { db.ChangeTracker.Clear(); return new(false, Code: "RESOURCE_VERSION_CONFLICT", Status: 409); } return new(true, response); }
    private async Task<string?> Validate(string name, string eventType, string endpoint, CancellationToken ct) { if (string.IsNullOrWhiteSpace(name) || name.Trim().Length > 200) return "VALIDATION_FAILED"; if (!catalog.Admits(eventType, IntegrationEventSchema.CurrentVersion)) return "EVENT_TYPE_INVALID"; return Uri.TryCreate(endpoint, UriKind.Absolute, out var uri) && await WebhookDestinationPolicy.IsSafeAsync(uri, resolver, ct) ? null : "ENDPOINT_NOT_ALLOWED"; }
    private async Task<AuthorizationContextDocument?> Authorize(AccessRequirement r, string c, CancellationToken ct) { var d = await access.AuthorizeAsync(r, c, ct); return d.IsAllowed ? d.Context : null; }
    private static OutboundWebhookSubscriptionDocument Project(OutboundWebhookSubscription x) => new(x.SubscriptionId, x.WorkspaceId, x.Name, x.EventType, x.EndpointUrl, x.Status, x.Version, x.CreatedAt, x.UpdatedAt, x.ArchivedAt); private static OutboundWebhookDeliveryDocument Project(OutboundWebhookDelivery x) => new(x.DeliveryId, x.SubscriptionId, x.EventId, x.EventType, x.Status, x.AttemptCount, x.NextAttemptAt, x.LastHttpStatus, x.LastErrorCode, x.CreatedAt, x.SucceededAt, x.DeadLetteredAt, x.Status == "DEAD_LETTER"); private static string Fingerprint<T>(T x) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes(JsonSerializer.Serialize(x, Json)))); private static string Scope(string w, string op, string key) => Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes($"{w}\n{op}\n{key}")));
    private async Task<WebhookResult<T>?> Replay<T>(string w, string op, string key, string fp, CancellationToken ct) where T : class { var r = await db.OutboundWebhookIdempotency.AsNoTracking().SingleOrDefaultAsync(x => x.ScopeKey == Scope(w, op, key), ct); if (r is null) return null; if (r.Fingerprint != fp) return new(false, Code: "IDEMPOTENCY_KEY_REUSED", Status: 409); return new(true, JsonSerializer.Deserialize<T>(r.ResponseJson, Json)); }
    private void Record<T>(AuthorizationContextDocument a, string op, string target, WebhookCommandContext c, string fp, T response) { db.OutboundWebhookIdempotency.Add(new(Scope(a.WorkspaceId, op, c.IdempotencyKey), a.WorkspaceId, op, c.IdempotencyKey, fp, JsonSerializer.Serialize(response, Json), clock.GetUtcNow())); db.OutboundWebhookAudit.Add(new(a.WorkspaceId, a.MemberId, op, target, c.CorrelationId, clock.GetUtcNow())); }
    private sealed class WebhookRuleException(string code, int status) : Exception { internal string Code => code; internal int Status => status; }
}
