<# Reproducible C6 relationship verification against an isolated SQL Server database and real ApiHost. #>
[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)][string] $DatabaseName,
    [string] $SqlServer = '(localdb)\MSSQLLocalDB',
    [int] $Port = 5371,
    [int] $ReadyTimeoutSeconds = 420,
    [switch] $KeepDatabase
)

$ErrorActionPreference = 'Stop'
Add-Type -AssemblyName System.Net.Http
$script:Passed = 0; $script:Failed = 0
$script:Results = New-Object System.Collections.ArrayList
$script:RequestCounter = 0
$script:BaseUrl = "http://127.0.0.1:$Port"

function Add-Result([string]$Name, [string]$Expected, [string]$Actual) {
    if ($Expected -eq $Actual) { $script:Passed++; [void]$script:Results.Add("PASS | $Name | $Actual") }
    else { $script:Failed++; [void]$script:Results.Add("FAIL | $Name | expected=$Expected actual=$Actual") }
}
function New-ConnectionString([string]$Database) { "Server=$SqlServer;Database=$Database;Trusted_Connection=True;TrustServerCertificate=True;MultipleActiveResultSets=True" }
function Invoke-Sql([string]$Query, [string]$Database = 'master') {
    $connection = New-Object System.Data.SqlClient.SqlConnection (New-ConnectionString $Database); $connection.Open()
    try { $command=$connection.CreateCommand(); $command.CommandText=$Query; $command.CommandTimeout=120; $reader=$command.ExecuteReader(); $rows=New-Object System.Collections.ArrayList
        while ($reader.Read()) { $row=@{}; for($i=0;$i-lt$reader.FieldCount;$i++){$name=$reader.GetName($i);if([string]::IsNullOrWhiteSpace($name)){$name="Value$i"};$row[$name]=$reader.GetValue($i)}; [void]$rows.Add([pscustomobject]$row) }; $reader.Close(); return $rows
    } finally { $connection.Close() }
}
function Invoke-SqlNonQuery([string]$Query, [string]$Database = $DatabaseName) {
    $connection = New-Object System.Data.SqlClient.SqlConnection (New-ConnectionString $Database); $connection.Open()
    try { $command=$connection.CreateCommand(); $command.CommandText=$Query; $command.CommandTimeout=120; [void]$command.ExecuteNonQuery() } finally { $connection.Close() }
}
function Get-Scalar([string]$Query, [string]$Database = $DatabaseName) { $rows=Invoke-Sql $Query $Database; if($rows.Count-eq 0){return $null}; $name=($rows[0].PSObject.Properties|Select-Object -First 1).Name; $rows[0].$name }
function Invoke-Api {
    param([string]$Method,[string]$Path,[string]$Body,[string]$Token,[string]$WorkspaceId,[string]$IdempotencyKey,[string]$IfMatch)
    $script:RequestCounter++; $request=New-Object System.Net.Http.HttpRequestMessage ([System.Net.Http.HttpMethod]::new($Method),"$script:BaseUrl$Path")
    [void]$request.Headers.TryAddWithoutValidation('X-Request-Id',('req-c6-{0:d8}' -f $script:RequestCounter)); [void]$request.Headers.TryAddWithoutValidation('X-Correlation-Id','corr-contact-relationships-c6')
    if($Token){[void]$request.Headers.TryAddWithoutValidation('Authorization',"Bearer $Token")}; if($WorkspaceId){[void]$request.Headers.TryAddWithoutValidation('X-Workspace-Id',$WorkspaceId)}
    if($IdempotencyKey){[void]$request.Headers.TryAddWithoutValidation('Idempotency-Key',$IdempotencyKey)}; if($IfMatch){[void]$request.Headers.TryAddWithoutValidation('If-Match',$IfMatch)}
    if($null-ne$Body){$request.Content=New-Object System.Net.Http.StringContent ($Body,[Text.Encoding]::UTF8,'application/json')}
    $handler=New-Object System.Net.Http.HttpClientHandler; $handler.UseProxy=$false; $handler.AllowAutoRedirect=$false; $client=New-Object System.Net.Http.HttpClient($handler,$true); $client.Timeout=[TimeSpan]::FromSeconds(60)
    try{$response=$client.SendAsync($request).GetAwaiter().GetResult();$raw=$response.Content.ReadAsStringAsync().GetAwaiter().GetResult();$status=[int]$response.StatusCode}finally{$client.Dispose();$request.Dispose()}
    $payload=$null;if($raw){try{$payload=$raw|ConvertFrom-Json}catch{}};[pscustomobject]@{Status=$status;Body=$payload;Raw=$raw}
}
function Call([string]$Method,[string]$Path,[string]$Body=$null,[string]$Key=$null,[long]$Version=-1) {
    $match=if($Version-ge 0){'"'+$Version+'"'}else{$null}; Invoke-Api $Method $Path $Body $script:Token $script:WorkspaceId $Key $match
}
function Start-ApiCommand([string]$Path,[string]$Body,[string]$Key,[long]$Version) {
    $script:RequestCounter++;$request=New-Object System.Net.Http.HttpRequestMessage ([System.Net.Http.HttpMethod]::Post,"$script:BaseUrl$Path")
    [void]$request.Headers.TryAddWithoutValidation('X-Request-Id',('req-c6-{0:d8}' -f $script:RequestCounter));[void]$request.Headers.TryAddWithoutValidation('X-Correlation-Id','corr-contact-relationships-c6');[void]$request.Headers.TryAddWithoutValidation('Authorization',"Bearer $script:Token");[void]$request.Headers.TryAddWithoutValidation('X-Workspace-Id',$script:WorkspaceId);[void]$request.Headers.TryAddWithoutValidation('Idempotency-Key',$Key);[void]$request.Headers.TryAddWithoutValidation('If-Match','"'+$Version+'"');$request.Content=New-Object System.Net.Http.StringContent ($Body,[Text.Encoding]::UTF8,'application/json')
    $handler=New-Object System.Net.Http.HttpClientHandler;$handler.UseProxy=$false;$client=New-Object System.Net.Http.HttpClient($handler,$true);$client.Timeout=[TimeSpan]::FromSeconds(60);[pscustomobject]@{Client=$client;Request=$request;Task=$client.SendAsync($request)}
}
function Complete-ApiCommand($Pending) { try{$response=$Pending.Task.GetAwaiter().GetResult();$raw=$response.Content.ReadAsStringAsync().GetAwaiter().GetResult();$status=[int]$response.StatusCode;$response.Dispose();[pscustomobject]@{Status=$status;Raw=$raw}}finally{$Pending.Client.Dispose();$Pending.Request.Dispose()} }
function Effects([string]$ContactId) { [string](Get-Scalar "SELECT CONCAT(Version,'|',(SELECT COUNT(*) FROM contacts.OrganizationRelationships WHERE ContactId='$ContactId'),'|',(SELECT COUNT(*) FROM contacts.CustomerRelationships WHERE ContactId='$ContactId'),'|',(SELECT COUNT(*) FROM contacts.AuditRecords WHERE AggregateId='$ContactId'),'|',(SELECT COUNT(*) FROM contacts.OutboxMessages WHERE AggregateId='$ContactId')) FROM contacts.Contacts WHERE ContactId='$ContactId'") }

$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$hostProject=Join-Path $root 'src/UnicoreCRM.ApiHost/UnicoreCRM.ApiHost.csproj'; $hostExe=Join-Path $root 'src/UnicoreCRM.ApiHost/bin/Debug/net10.0/UnicoreCRM.ApiHost.exe'; $contentRoot=Join-Path $root 'src/UnicoreCRM.ApiHost'; $crmProject=Join-Path $root 'src/UnicoreCRM.Crm/UnicoreCRM.Crm.csproj'
$email='contact.relationships.c6@example.test';$password='Contact-Relationships-C6!2026';$hostProcess=$null;$logPath=Join-Path ([IO.Path]::GetTempPath()) "unicore-c6-$([Guid]::NewGuid().ToString('N')).log"
$contactA='contact_c6_a';$contactB='contact_c6_b';$contactC='contact_c6_concurrent_c';$contactD='contact_c6_concurrent_d';$contactArchived='contact_c6_archived';$orgA='organization_c6_a';$orgB='organization_c6_b';$orgC='organization_c6_concurrent_c';$orgD='organization_c6_concurrent_d';$orgForeign='organization_c6_foreign';$customerA='customer_c6_a';$customerB='customer_c6_b';$customerC='customer_c6_concurrent';$customerForeign='customer_c6_foreign';$foreignWorkspace='ws_contact_c6_foreign'
try {
    Invoke-SqlNonQuery "IF DB_ID('$DatabaseName') IS NOT NULL BEGIN ALTER DATABASE [$DatabaseName] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [$DatabaseName]; END; CREATE DATABASE [$DatabaseName];" 'master'
    $env:ASPNETCORE_ENVIRONMENT='Development';$env:DOTNET_ENVIRONMENT='Development';$env:ASPNETCORE_URLS=$script:BaseUrl;$env:ConnectionStrings__UnicoreCRM=New-ConnectionString $DatabaseName;$env:Development__ApplyMigrations='true';$env:UNICORE_DEV_SEED_ENABLED='false'
    $env:IdentityAuth__EmailVerification__Sender__Kind='DevelopmentLog';$env:IdentityAuth__DevelopmentBootstrap__Enabled='true';$env:IdentityAuth__DevelopmentBootstrap__Email=$email;$env:IdentityAuth__DevelopmentBootstrap__Password=$password;$env:IdentityAuth__DevelopmentBootstrap__DisplayName='C6 Verifier';$env:IdentityAuth__Jwt__SigningKey=[Guid]::NewGuid().ToString('N')+[Guid]::NewGuid().ToString('N');$env:IdentityAuth__RefreshTokenPepper=[Guid]::NewGuid().ToString('N')+[Guid]::NewGuid().ToString('N');$env:Workspace__DevelopmentBootstrap__Enabled='false';$env:AccessControl__DevelopmentBootstrap__Enabled='false';$env:Workflows__InitialWorkspaceProvisioning__ResumeEnabled='false';$env:AI__Provider__Kind='DevelopmentDeterministic'
    Push-Location $root;try{& dotnet build $hostProject -v q --nologo|Out-Null;if($LASTEXITCODE-ne 0){throw 'build failed'};& dotnet ef database update --project $crmProject --context OrganizationsDbContext --connection (New-ConnectionString $DatabaseName) --no-build|Out-Null;if($LASTEXITCODE-ne 0){throw 'Organizations migration failed'};& dotnet ef database update 20260908062648_ContactAuthoritativeWrites --project $crmProject --context ContactsDbContext --connection (New-ConnectionString $DatabaseName) --no-build|Out-Null;if($LASTEXITCODE-ne 0){throw 'pre-C6 migration failed'}}finally{Pop-Location}
    Invoke-SqlNonQuery @"
INSERT organizations.Organizations(OrganizationId,WorkspaceId,DisplayName,Status,Version,CreatedAt,UpdatedAt,Profile) VALUES
('org_c6_legacy','ws_c6_legacy','Legacy Organization','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{}'),
('org_c6_legacy_dup','ws_c6_legacy','Legacy Duplicate Target','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{}'),
('org_c6_legacy_foreign','ws_c6_other','Legacy Foreign Target','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{}');
INSERT contacts.Contacts(ContactId,WorkspaceId,OwnerId,FullName,Status,Version,CreatedAt,UpdatedAt,Profile) VALUES
('contact_c6_legacy_valid','ws_c6_legacy',NULL,'Legacy Valid','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"organizationRelationships":[{"id":"rel_c6_legacy_valid","organizationAccountId":"org_c6_legacy","role":"employee","isPrimaryRepresentative":true,"effectiveFrom":"2026-01-01T00:00:00Z","createdAt":"2026-01-01T00:00:00Z","createdBy":"legacy_actor"}]}'),
('contact_c6_legacy_invalid','ws_c6_legacy',NULL,'Legacy Invalid','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"organizationRelationships":[{"id":"rel_c6_legacy_invalid","role":"employee","effectiveFrom":"2026-01-01T00:00:00Z","createdAt":"2026-01-01T00:00:00Z"}]}'),
('contact_c6_legacy_malformed','ws_c6_legacy',NULL,'Legacy Malformed','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{malformed'),
('contact_c6_legacy_missing_target','ws_c6_legacy',NULL,'Legacy Missing Target','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"organizationRelationships":[{"id":"rel_c6_legacy_missing","organizationAccountId":"org_c6_missing","role":"employee","effectiveFrom":"2026-01-01T00:00:00Z","createdAt":"2026-01-01T00:00:00Z"}]}'),
('contact_c6_legacy_foreign_target','ws_c6_legacy',NULL,'Legacy Foreign Target','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"organizationRelationships":[{"id":"rel_c6_legacy_foreign","organizationAccountId":"org_c6_legacy_foreign","role":"employee","effectiveFrom":"2026-01-01T00:00:00Z","createdAt":"2026-01-01T00:00:00Z"}]}'),
('contact_c6_legacy_case_role','ws_c6_legacy',NULL,'Legacy Case Role','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"organizationRelationships":[{"id":"rel_c6_legacy_case_role","organizationAccountId":"org_c6_legacy","role":"Employee","effectiveFrom":"2026-01-01T00:00:00Z","createdAt":"2026-01-01T00:00:00Z"}]}'),
('contact_c6_legacy_duplicate','ws_c6_legacy',NULL,'Legacy Duplicate','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"organizationRelationships":[{"id":"rel_c6_dup_a","organizationAccountId":"org_c6_legacy_dup","role":"employee","effectiveFrom":"2026-01-01T00:00:00Z","createdAt":"2026-01-01T00:00:00Z"},{"id":"rel_c6_dup_b","organizationAccountId":"org_c6_legacy_dup","role":"advisor","effectiveFrom":"2026-02-01T00:00:00Z","createdAt":"2026-02-01T00:00:00Z"}]}'),
('contact_c6_legacy_ended','ws_c6_legacy',NULL,'Legacy Ended','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"organizationRelationships":[{"id":"rel_c6_legacy_ended","organizationAccountId":"org_c6_legacy","role":"advisor","effectiveFrom":"2025-01-01T00:00:00Z","effectiveTo":"2025-06-01T00:00:00Z","endedReason":"Historical","createdAt":"2025-01-01T00:00:00Z"}]}');
"@
    Push-Location $root;try{& dotnet run --no-build --no-launch-profile --project $hostProject -- --migrate|Out-Null;if($LASTEXITCODE-ne 0){throw 'migration failed'};$migrationState=[string](Get-Scalar "SELECT CONCAT((SELECT COUNT(*) FROM contacts.OrganizationRelationships WHERE RelationshipId='rel_c6_legacy_valid'),'|',(SELECT COUNT(*) FROM contacts.RelationshipMigrationIssues WHERE ContactId='contact_c6_legacy_invalid'))");& dotnet run --no-build --no-launch-profile --project $hostProject -- --migrate|Out-Null;if($LASTEXITCODE-ne 0){throw 'repeat migration failed'};& dotnet run --no-build --no-launch-profile --project $hostProject -- --seed-demo|Out-Null;if($LASTEXITCODE-ne 0){throw 'seed failed'}}finally{Pop-Location}
    Add-Result 'legacy valid relationship backfilled and invalid evidence quarantined' '1|1' $migrationState
    Add-Result 'malformed legacy profile quarantined without aborting migration' '1' ([string](Get-Scalar "SELECT COUNT(*) FROM contacts.RelationshipMigrationIssues WHERE ContactId='contact_c6_legacy_malformed' AND IssueCode='INVALID_PROFILE_JSON'"))
    Add-Result 'missing and foreign Organization targets quarantined' '2' ([string](Get-Scalar "SELECT COUNT(*) FROM contacts.RelationshipMigrationIssues WHERE ContactId IN ('contact_c6_legacy_missing_target','contact_c6_legacy_foreign_target') AND IssueCode='INVALID_OR_UNVERIFIED_ORGANIZATION_TARGET'"))
    Add-Result 'case-invalid controlled role quarantined without aborting migration' '1|0' ([string](Get-Scalar "SELECT CONCAT((SELECT COUNT(*) FROM contacts.RelationshipMigrationIssues WHERE ContactId='contact_c6_legacy_case_role' AND IssueCode='INVALID_ROLE'),'|',(SELECT COUNT(*) FROM contacts.OrganizationRelationships WHERE ContactId='contact_c6_legacy_case_role'))"))
    Add-Result 'duplicate active legacy pair quarantined without partial promotion' '2|0' ([string](Get-Scalar "SELECT CONCAT((SELECT COUNT(*) FROM contacts.RelationshipMigrationIssues WHERE ContactId='contact_c6_legacy_duplicate' AND IssueCode='DUPLICATE_ACTIVE_PAIR'),'|',(SELECT COUNT(*) FROM contacts.OrganizationRelationships WHERE ContactId='contact_c6_legacy_duplicate'))"))
    Add-Result 'valid ended legacy relationship preserves history' '1|Historical' ([string](Get-Scalar "SELECT CONCAT(CASE WHEN EffectiveTo IS NULL THEN 0 ELSE 1 END,'|',EndedReason) FROM contacts.OrganizationRelationships WHERE RelationshipId='rel_c6_legacy_ended'"))
    Add-Result 'migration rerun is idempotent' $migrationState ([string](Get-Scalar "SELECT CONCAT((SELECT COUNT(*) FROM contacts.OrganizationRelationships WHERE RelationshipId='rel_c6_legacy_valid'),'|',(SELECT COUNT(*) FROM contacts.RelationshipMigrationIssues WHERE ContactId='contact_c6_legacy_invalid'))"))
    Add-Result 'legacy primary-representative does not become primary affiliation authority' '0' ([string](Get-Scalar "SELECT CAST(IsPrimaryAffiliation AS int) FROM contacts.OrganizationRelationships WHERE RelationshipId='rel_c6_legacy_valid'"))
    Add-Result 'C6 relationship tables migrated' '2' ([string](Get-Scalar "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='contacts' AND TABLE_NAME IN ('OrganizationRelationships','CustomerRelationships')"))
    Add-Result 'C6 filtered unique indexes migrated' '4' ([string](Get-Scalar "SELECT COUNT(*) FROM sys.indexes i JOIN sys.tables t ON t.object_id=i.object_id JOIN sys.schemas s ON s.schema_id=t.schema_id WHERE s.name='contacts' AND i.is_unique=1 AND i.has_filter=1 AND t.name IN ('OrganizationRelationships','CustomerRelationships')"))
    $hostProcess=Start-Process -FilePath $hostExe -WorkingDirectory $contentRoot -PassThru -WindowStyle Hidden -RedirectStandardOutput $logPath -RedirectStandardError "$logPath.err"
    $ready=$false;for($i=0;$i-lt$ReadyTimeoutSeconds;$i++){Start-Sleep -Seconds 1;if($hostProcess.HasExited){throw "host exited $($hostProcess.ExitCode)"};try{if((Invoke-Api 'GET' '/auth/session').Status-gt 0){$ready=$true;break}}catch{}};if(-not$ready){throw 'host readiness timeout'}
    Add-Result 'anonymous relationship mutation denied' '401' ([string](Invoke-Api 'POST' "/contacts/$contactA/organization-relationships" '{}' $null 'ws_unknown' 'idem-c6-anon' '"0"').Status)
    $signIn=Invoke-Api 'POST' '/auth/sessions' (@{email=$email;password=$password}|ConvertTo-Json -Compress) $null $null 'idem-c6-signin';if($signIn.Status-ne 200){throw "signin $($signIn.Raw)"};$script:Token=$signIn.Body.accessToken
    $session=Invoke-Api 'GET' '/auth/session' $null $script:Token; $memberId=$session.Body.principal.memberId
    $provision=Invoke-Api 'POST' '/workspaces/initial-provisioning' '{"name":"C6 Relationship Workspace"}' $script:Token $null 'idem-c6-provision';if($provision.Status-ne 201){throw "provision $($provision.Raw)"};$script:WorkspaceId=$provision.Body.workspaceId
    $roleId=Get-Scalar "SELECT RoleId FROM access.Roles WHERE WorkspaceId='$($script:WorkspaceId)' AND Name='Workspace Owner'"
    Invoke-SqlNonQuery @"
IF NOT EXISTS(SELECT 1 FROM workspace.Workspaces WHERE WorkspaceId='$foreignWorkspace') INSERT workspace.Workspaces(WorkspaceId,[Key],Name,LogoText,CreatedAt) VALUES('$foreignWorkspace','c6-foreign','C6 Foreign','CF',SYSUTCDATETIME());
INSERT contacts.Contacts(ContactId,WorkspaceId,OwnerId,FullName,Status,Version,CreatedAt,UpdatedAt,ArchivedAt,Profile) VALUES
('$contactA','$($script:WorkspaceId)','$memberId','C6 Contact A','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),NULL,N'{"organizationRelationships":[]}'),
('$contactB','$($script:WorkspaceId)','$memberId','C6 Contact B','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),NULL,N'{}'),
('$contactC','$($script:WorkspaceId)','$memberId','C6 Concurrent C','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),NULL,N'{}'),
('$contactD','$($script:WorkspaceId)','$memberId','C6 Concurrent D','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),NULL,N'{}'),
('$contactArchived','$($script:WorkspaceId)','$memberId','C6 Archived','archived',0,SYSUTCDATETIME(),SYSUTCDATETIME(),SYSUTCDATETIME(),N'{}');
INSERT organizations.Organizations(OrganizationId,WorkspaceId,DisplayName,Status,Version,CreatedAt,UpdatedAt,Profile) VALUES
('$orgA','$($script:WorkspaceId)','C6 Organization A','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"ownerId":"$memberId"}'),
('$orgB','$($script:WorkspaceId)','C6 Organization B','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"ownerId":"$memberId"}'),
('$orgC','$($script:WorkspaceId)','C6 Organization Concurrent C','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"ownerId":"$memberId"}'),
('$orgD','$($script:WorkspaceId)','C6 Organization Concurrent D','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"ownerId":"$memberId"}'),
('$orgForeign','$foreignWorkspace','C6 FOREIGN SECRET','active',0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{}');
INSERT customers.Customers(WorkspaceId,CustomerId,CustomerCode,Type,RelationshipType,RelationshipId,Status,Health,FirstPurchaseAt,LastPurchaseAt,Version,CreatedAt,UpdatedAt,Profile) VALUES
('$($script:WorkspaceId)','$customerA','CUS-C6-A','B2C','CONTACT','$contactA','ACTIVE','GOOD',SYSUTCDATETIME(),SYSUTCDATETIME(),0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"careOwnerId":"$memberId"}'),
('$($script:WorkspaceId)','$customerB','CUS-C6-B','B2B','ORGANIZATION_ACCOUNT','$orgA','ACTIVE','GOOD',SYSUTCDATETIME(),SYSUTCDATETIME(),0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"careOwnerId":"$memberId"}'),
('$($script:WorkspaceId)','$customerC','CUS-C6-CONCURRENT','B2B','ORGANIZATION_ACCOUNT','$orgC','ACTIVE','GOOD',SYSUTCDATETIME(),SYSUTCDATETIME(),0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{"careOwnerId":"$memberId"}'),
('$foreignWorkspace','$customerForeign','CUS-C6-FOREIGN','B2C','CONTACT','foreign-subject','ACTIVE','GOOD',SYSUTCDATETIME(),SYSUTCDATETIME(),0,SYSUTCDATETIME(),SYSUTCDATETIME(),N'{}');
IF NOT EXISTS(SELECT 1 FROM access.RoleCapabilities WHERE RoleId='$roleId' AND Capability='organizations.read') INSERT access.RoleCapabilities(RoleId,Capability) VALUES('$roleId','organizations.read');
IF NOT EXISTS(SELECT 1 FROM access.RoleCapabilities WHERE RoleId='$roleId' AND Capability='customers.view') INSERT access.RoleCapabilities(RoleId,Capability) VALUES('$roleId','customers.view');
DELETE access.RoleDataScopes WHERE RoleId='$roleId' AND ResourceKey IN ('contacts','organizations','customers');
INSERT access.RoleDataScopes(PolicyId,WorkspaceId,RoleId,ResourceKey,Scope,AllowedOwnerIdsJson) VALUES
('scope_c6_contacts','$($script:WorkspaceId)','$roleId','contacts','Workspace','[]'),('scope_c6_orgs','$($script:WorkspaceId)','$roleId','organizations','Workspace','[]'),('scope_c6_customers','$($script:WorkspaceId)','$roleId','customers','Workspace','[]');
"@
    $missing='organization_c6_unknown';$before=Effects $contactA
    $x=Call 'POST' "/contacts/$contactA/organization-relationships" (@{organizationId=$missing;role='employee'}|ConvertTo-Json -Compress) 'idem-c6-org-unknown' 0
    Add-Result 'unknown Organization hidden' '404|RESOURCE_NOT_FOUND' "$($x.Status)|$($x.Body.code)"
    Add-Result 'unknown target denial has zero effects' $before (Effects $contactA)
    $x=Call 'POST' "/contacts/$contactA/organization-relationships" (@{organizationId=$orgForeign;role='employee'}|ConvertTo-Json -Compress) 'idem-c6-org-foreign' 0;Add-Result 'cross-workspace Organization hidden without identity leak' '404|False' "$($x.Status)|$($x.Raw -match 'C6 FOREIGN SECRET')"
    Invoke-SqlNonQuery "DELETE access.RoleCapabilities WHERE RoleId='$roleId' AND Capability='contacts.update'";$before=Effects $contactA;$x=Call 'POST' "/contacts/$contactA/organization-relationships" (@{organizationId=$orgA;role='employee'}|ConvertTo-Json -Compress) 'idem-c6-no-update' 0;Add-Result 'missing contacts.update denied' '403|ACCESS_DENIED' "$($x.Status)|$($x.Body.code)";Add-Result 'contacts.update denial has zero effects' $before (Effects $contactA);Invoke-SqlNonQuery "INSERT access.RoleCapabilities(RoleId,Capability) VALUES('$roleId','contacts.update')"
    Invoke-SqlNonQuery "DELETE access.RoleCapabilities WHERE RoleId='$roleId' AND Capability='organizations.read'";$before=Effects $contactA;$hidden=Call 'POST' "/contacts/$contactA/organization-relationships" (@{organizationId=$orgA;role='employee'}|ConvertTo-Json -Compress) 'idem-c6-no-org-read' 0;Add-Result 'missing target visibility concealed' '404|RESOURCE_NOT_FOUND' "$($hidden.Status)|$($hidden.Body.code)";Add-Result 'target visibility denial has zero effects' $before (Effects $contactA);Invoke-SqlNonQuery "INSERT access.RoleCapabilities(RoleId,Capability) VALUES('$roleId','organizations.read')"
    $org1=Call 'POST' "/contacts/$contactA/organization-relationships" (@{organizationId=$orgA;role='employee';isPrimaryAffiliation=$true}|ConvertTo-Json -Compress) 'idem-c6-org-a' 0;Add-Result 'authorized primary Organization link succeeds' '200|1' "$($org1.Status)|$($org1.Body.version)";$orgRelA=[string](Get-Scalar "SELECT RelationshipId FROM contacts.OrganizationRelationships WHERE ContactId='$contactA' AND OrganizationId='$orgA' AND EffectiveTo IS NULL")
    $orgReplay=Call 'POST' "/contacts/$contactA/organization-relationships" (@{organizationId=$orgA;role='employee';isPrimaryAffiliation=$true}|ConvertTo-Json -Compress) 'idem-c6-org-a' 0;Add-Result 'exact replay is replayed' '200|REPLAYED' "$($orgReplay.Status)|$($orgReplay.Body.outcome)";Add-Result 'replay duplicates no relationship/audit/outbox' '1|1|1' ([string](Get-Scalar "SELECT CONCAT((SELECT COUNT(*) FROM contacts.OrganizationRelationships WHERE ContactId='$contactA'), '|',(SELECT COUNT(*) FROM contacts.AuditRecords WHERE AggregateId='$contactA' AND Operation='createContactOrganizationRelationship'),'|',(SELECT COUNT(*) FROM contacts.OutboxMessages WHERE AggregateId='$contactA' AND EventType='CONTACT_ORGANIZATION_RELATIONSHIP_CREATED') )"))
    $reuse=Call 'POST' "/contacts/$contactA/organization-relationships" (@{organizationId=$orgA;role='advisor'}|ConvertTo-Json -Compress) 'idem-c6-org-a' 0;Add-Result 'changed replay payload conflicts' '409|IDEMPOTENCY_KEY_REUSED' "$($reuse.Status)|$($reuse.Body.code)"
    $duplicate=Call 'POST' "/contacts/$contactA/organization-relationships" (@{organizationId=$orgA;role='advisor'}|ConvertTo-Json -Compress) 'idem-c6-org-dup' 1;Add-Result 'duplicate active Organization pair rejected' '409|RELATIONSHIP_CONFLICT' "$($duplicate.Status)|$($duplicate.Body.code)"
    $org2=Call 'POST' "/contacts/$contactA/organization-relationships" (@{organizationId=$orgB;role='executive';isPrimaryAffiliation=$true}|ConvertTo-Json -Compress) 'idem-c6-org-b' 1;Add-Result 'Contact supports multiple Organizations' '200|2' "$($org2.Status)|$($org2.Body.version)";$orgRelB=[string](Get-Scalar "SELECT RelationshipId FROM contacts.OrganizationRelationships WHERE ContactId='$contactA' AND OrganizationId='$orgB' AND EffectiveTo IS NULL");Add-Result 'primary switch leaves exactly one primary affiliation' '1' ([string](Get-Scalar "SELECT COUNT(*) FROM contacts.OrganizationRelationships WHERE ContactId='$contactA' AND EffectiveTo IS NULL AND IsPrimaryAffiliation=1"));Add-Result 'primary switch demotes old affiliation' '0' ([string](Get-Scalar "SELECT CAST(IsPrimaryAffiliation AS int) FROM contacts.OrganizationRelationships WHERE RelationshipId='$orgRelA'"))
    $orgOther=Call 'POST' "/contacts/$contactB/organization-relationships" (@{organizationId=$orgA;role='buyer'}|ConvertTo-Json -Compress) 'idem-c6-org-many' 0;Add-Result 'Organization supports multiple Contacts' '200' ([string]$orgOther.Status)
    $stale=Call 'PATCH' "/contacts/$contactA/organization-relationships/$orgRelB" '{"role":"advisor"}' 'idem-c6-stale' 1;Add-Result 'stale relationship update conflicts' '409|RESOURCE_VERSION_CONFLICT' "$($stale.Status)|$($stale.Body.code)";Add-Result 'stale update does not overwrite role' 'executive' ([string](Get-Scalar "SELECT Role FROM contacts.OrganizationRelationships WHERE RelationshipId='$orgRelB'"))
    $updated=Call 'PATCH' "/contacts/$contactA/organization-relationships/$orgRelB" '{"role":"advisor"}' 'idem-c6-org-update' 2;Add-Result 'current Organization relationship update succeeds' '200|3|advisor' "$($updated.Status)|$($updated.Body.version)|$([string](Get-Scalar "SELECT Role FROM contacts.OrganizationRelationships WHERE RelationshipId='$orgRelB'"))"
    $orgUpdatedSummary=Call 'GET' "/contacts/$contactA/relationship-summary";$orgUpdatedProjection=$orgUpdatedSummary.Body.organizationRelationships|Where-Object relationshipId -eq $orgRelB;Add-Result 'summary immediately reflects Organization role update' '200|advisor|active' "$($orgUpdatedSummary.Status)|$($orgUpdatedProjection.role)|$($orgUpdatedProjection.status)"
    $before=Effects $contactA;$unknownCustomer=Call 'POST' "/contacts/$contactA/customer-relationships" '{"customerId":"customer_c6_unknown","role":"support"}' 'idem-c6-cust-unknown' 3;Add-Result 'unknown Customer hidden' '404|RESOURCE_NOT_FOUND' "$($unknownCustomer.Status)|$($unknownCustomer.Body.code)";Add-Result 'unknown Customer denial has zero effects' $before (Effects $contactA)
    $foreignCustomer=Call 'POST' "/contacts/$contactA/customer-relationships" (@{customerId=$customerForeign;role='support'}|ConvertTo-Json -Compress) 'idem-c6-cust-foreign' 3;Add-Result 'cross-workspace Customer hidden without identity leak' '404|False' "$($foreignCustomer.Status)|$($foreignCustomer.Raw -match 'CUS-C6-FOREIGN')"
    Invoke-SqlNonQuery "DELETE access.RoleCapabilities WHERE RoleId='$roleId' AND Capability='customers.view'";$before=Effects $contactA;$hiddenCustomer=Call 'POST' "/contacts/$contactA/customer-relationships" (@{customerId=$customerA;role='support'}|ConvertTo-Json -Compress) 'idem-c6-no-customer-read' 3;Add-Result 'missing Customer target visibility concealed' '404|RESOURCE_NOT_FOUND' "$($hiddenCustomer.Status)|$($hiddenCustomer.Body.code)";Add-Result 'Customer target visibility denial has zero effects' $before (Effects $contactA);Invoke-SqlNonQuery "INSERT access.RoleCapabilities(RoleId,Capability) VALUES('$roleId','customers.view')"
    $cust1=Call 'POST' "/contacts/$contactA/customer-relationships" (@{customerId=$customerA;role='primary_contact'}|ConvertTo-Json -Compress) 'idem-c6-cust-a' 3;Add-Result 'B2C stakeholder link succeeds without changing account subject' '200|CONTACT' "$($cust1.Status)|$([string](Get-Scalar "SELECT RelationshipType FROM customers.Customers WHERE CustomerId='$customerA'"))";$custRelA=[string](Get-Scalar "SELECT RelationshipId FROM contacts.CustomerRelationships WHERE ContactId='$contactA' AND CustomerId='$customerA' AND EffectiveTo IS NULL")
    $cust2=Call 'POST' "/contacts/$contactA/customer-relationships" (@{customerId=$customerB;role='billing'}|ConvertTo-Json -Compress) 'idem-c6-cust-b' 4;Add-Result 'Contact supports multiple Customers' '200' ([string]$cust2.Status);$custRelB=[string](Get-Scalar "SELECT RelationshipId FROM contacts.CustomerRelationships WHERE ContactId='$contactA' AND CustomerId='$customerB' AND EffectiveTo IS NULL")
    $custOther=Call 'POST' "/contacts/$contactB/customer-relationships" (@{customerId=$customerA;role='support'}|ConvertTo-Json -Compress) 'idem-c6-cust-many' 1;Add-Result 'Customer supports multiple stakeholder Contacts' '200' ([string]$custOther.Status);$custOtherId=[string](Get-Scalar "SELECT RelationshipId FROM contacts.CustomerRelationships WHERE ContactId='$contactB' AND CustomerId='$customerA' AND EffectiveTo IS NULL")
    $primaryConflict=Call 'PATCH' "/contacts/$contactB/customer-relationships/$custOtherId" '{"role":"primary_contact"}' 'idem-c6-primary-conflict' 2;Add-Result 'second Customer primary_contact rejected' '409|RELATIONSHIP_CONFLICT' "$($primaryConflict.Status)|$($primaryConflict.Body.code)";Add-Result 'database retains one Customer primary_contact' '1' ([string](Get-Scalar "SELECT COUNT(*) FROM contacts.CustomerRelationships WHERE CustomerId='$customerA' AND EffectiveTo IS NULL AND Role='primary_contact'"))
    $duplicateCustomer=Call 'POST' "/contacts/$contactA/customer-relationships" (@{customerId=$customerB;role='support'}|ConvertTo-Json -Compress) 'idem-c6-cust-duplicate' 5;Add-Result 'duplicate active Contact Customer pair rejected' '409|RELATIONSHIP_CONFLICT' "$($duplicateCustomer.Status)|$($duplicateCustomer.Body.code)"
    $staleCustomer=Call 'PATCH' "/contacts/$contactA/customer-relationships/$custRelB" '{"role":"technical"}' 'idem-c6-cust-update-stale' 4;Add-Result 'stale Customer relationship update conflicts' '409|RESOURCE_VERSION_CONFLICT' "$($staleCustomer.Status)|$($staleCustomer.Body.code)"
    $updatedCustomer=Call 'PATCH' "/contacts/$contactA/customer-relationships/$custRelB" '{"role":"technical"}' 'idem-c6-cust-update' 5;Add-Result 'current Customer relationship update succeeds' '200|6|technical' "$($updatedCustomer.Status)|$($updatedCustomer.Body.version)|$([string](Get-Scalar "SELECT Role FROM contacts.CustomerRelationships WHERE RelationshipId='$custRelB'"))"
    $customerUpdatedSummary=Call 'GET' "/contacts/$contactA/relationship-summary";$customerUpdatedProjection=$customerUpdatedSummary.Body.customerRelationships|Where-Object relationshipId -eq $custRelB;Add-Result 'summary immediately reflects Customer role update' '200|technical|active' "$($customerUpdatedSummary.Status)|$($customerUpdatedProjection.role)|$($customerUpdatedProjection.status)"
    $endedCustomer=Call 'POST' "/contacts/$contactA/customer-relationships/$custRelB/end" '{"endedReason":"Stakeholder changed"}' 'idem-c6-cust-end' 6;Add-Result 'Customer relationship end preserves history' '200|7|1' "$($endedCustomer.Status)|$($endedCustomer.Body.version)|$([string](Get-Scalar "SELECT COUNT(*) FROM contacts.CustomerRelationships WHERE RelationshipId='$custRelB' AND EffectiveTo IS NOT NULL AND EndedReason='Stakeholder changed'"))"
    $customerEndedSummary=Call 'GET' "/contacts/$contactA/relationship-summary";$customerEndedProjection=$customerEndedSummary.Body.customerRelationships|Where-Object relationshipId -eq $custRelB;Add-Result 'summary immediately reflects Customer end reason and history' '200|ended|Stakeholder changed' "$($customerEndedSummary.Status)|$($customerEndedProjection.status)|$($customerEndedProjection.endedReason)"
    $customerEndReplay=Call 'POST' "/contacts/$contactA/customer-relationships/$custRelB/end" '{"endedReason":"Stakeholder changed"}' 'idem-c6-cust-end' 6;Add-Result 'Customer end exact replay survives ended state' '200|REPLAYED' "$($customerEndReplay.Status)|$($customerEndReplay.Body.outcome)"
    $customerUpdateReplay=Call 'PATCH' "/contacts/$contactA/customer-relationships/$custRelB" '{"role":"technical"}' 'idem-c6-cust-update' 5;Add-Result 'Customer update exact replay survives later end' '200|REPLAYED' "$($customerUpdateReplay.Status)|$($customerUpdateReplay.Body.outcome)"
    $customerCreateReplay=Call 'POST' "/contacts/$contactA/customer-relationships" (@{customerId=$customerA;role='primary_contact'}|ConvertTo-Json -Compress) 'idem-c6-cust-a' 3;Add-Result 'Customer create exact replay is stable after later mutations' '200|REPLAYED' "$($customerCreateReplay.Status)|$($customerCreateReplay.Body.outcome)"
    $customerRelink=Call 'POST' "/contacts/$contactA/customer-relationships" (@{customerId=$customerB;role='billing'}|ConvertTo-Json -Compress) 'idem-c6-cust-relink' 7;Add-Result 'ended Customer pair can relink without deleting history' '200|2' "$($customerRelink.Status)|$([string](Get-Scalar "SELECT COUNT(*) FROM contacts.CustomerRelationships WHERE ContactId='$contactA' AND CustomerId='$customerB'"))"
    $parallelOrg1=Start-ApiCommand "/contacts/$contactC/organization-relationships" (@{organizationId=$orgC;role='employee';isPrimaryAffiliation=$true}|ConvertTo-Json -Compress) 'idem-c6-concurrent-org-c' 0;$parallelOrg2=Start-ApiCommand "/contacts/$contactC/organization-relationships" (@{organizationId=$orgD;role='executive';isPrimaryAffiliation=$true}|ConvertTo-Json -Compress) 'idem-c6-concurrent-org-d' 0;[System.Threading.Tasks.Task]::WaitAll([System.Threading.Tasks.Task[]]@($parallelOrg1.Task,$parallelOrg2.Task));$parallelOrgResults=@((Complete-ApiCommand $parallelOrg1).Status,(Complete-ApiCommand $parallelOrg2).Status)|Sort-Object;Add-Result 'concurrent same-version Contact mutations yield one commit and one conflict' '200,409' ($parallelOrgResults-join ',');Add-Result 'concurrent primary affiliation leaves one durable primary and version' '1|1|1' ([string](Get-Scalar "SELECT CONCAT((SELECT COUNT(*) FROM contacts.OrganizationRelationships WHERE ContactId='$contactC'),'|',(SELECT COUNT(*) FROM contacts.OrganizationRelationships WHERE ContactId='$contactC' AND EffectiveTo IS NULL AND IsPrimaryAffiliation=1),'|',(SELECT Version FROM contacts.Contacts WHERE ContactId='$contactC'))"))
    $parallelCustomer1=Start-ApiCommand "/contacts/$contactC/customer-relationships" (@{customerId=$customerC;role='primary_contact'}|ConvertTo-Json -Compress) 'idem-c6-concurrent-customer-c' 1;$parallelCustomer2=Start-ApiCommand "/contacts/$contactD/customer-relationships" (@{customerId=$customerC;role='primary_contact'}|ConvertTo-Json -Compress) 'idem-c6-concurrent-customer-d' 0;[System.Threading.Tasks.Task]::WaitAll([System.Threading.Tasks.Task[]]@($parallelCustomer1.Task,$parallelCustomer2.Task));$parallelCustomerResults=@((Complete-ApiCommand $parallelCustomer1).Status,(Complete-ApiCommand $parallelCustomer2).Status)|Sort-Object;Add-Result 'concurrent Customer primary requests yield one commit and one conflict' '200,409' ($parallelCustomerResults-join ',');Add-Result 'concurrent Customer primary leaves exactly one durable primary' '1' ([string](Get-Scalar "SELECT COUNT(*) FROM contacts.CustomerRelationships WHERE CustomerId='$customerC' AND EffectiveTo IS NULL AND Role='primary_contact'"))
    $summary=Call 'GET' "/contacts/$contactA/relationship-summary";Add-Result 'authoritative summary reflects Customer update end and relink immediately' '200|2|3|8' "$($summary.Status)|$($summary.Body.organizationRelationships.Count)|$($summary.Body.customerRelationships.Count)|$($summary.Body.projectionVersion)";Add-Result 'B2C account subject not manufactured as duplicate stakeholder' '1' ([string](Get-Scalar "SELECT COUNT(*) FROM contacts.CustomerRelationships WHERE ContactId='$contactA' AND CustomerId='$customerA'"))
    $ended=Call 'POST' "/contacts/$contactA/organization-relationships/$orgRelB/end" '{"endedReason":"Affiliation concluded"}' 'idem-c6-org-end' 8;Add-Result 'Organization relationship end succeeds' '200|ended|9' "$($ended.Status)|$([string](Get-Scalar "SELECT CASE WHEN EffectiveTo IS NULL THEN 'active' ELSE 'ended' END FROM contacts.OrganizationRelationships WHERE RelationshipId='$orgRelB'"))|$($ended.Body.version)";Add-Result 'end preserves historical row' '1' ([string](Get-Scalar "SELECT COUNT(*) FROM contacts.OrganizationRelationships WHERE RelationshipId='$orgRelB' AND EffectiveTo IS NOT NULL AND EndedReason='Affiliation concluded'"))
    $orgEndedSummary=Call 'GET' "/contacts/$contactA/relationship-summary";$orgEndedProjection=$orgEndedSummary.Body.organizationRelationships|Where-Object relationshipId -eq $orgRelB;Add-Result 'summary immediately reflects Organization end reason and history' '200|ended|Affiliation concluded' "$($orgEndedSummary.Status)|$($orgEndedProjection.status)|$($orgEndedProjection.endedReason)"
    $orgEndReplay=Call 'POST' "/contacts/$contactA/organization-relationships/$orgRelB/end" '{"endedReason":"Affiliation concluded"}' 'idem-c6-org-end' 8;Add-Result 'Organization end exact replay survives ended state' '200|REPLAYED' "$($orgEndReplay.Status)|$($orgEndReplay.Body.outcome)"
    $orgUpdateReplay=Call 'PATCH' "/contacts/$contactA/organization-relationships/$orgRelB" '{"role":"advisor"}' 'idem-c6-org-update' 2;Add-Result 'Organization update exact replay survives later end' '200|REPLAYED' "$($orgUpdateReplay.Status)|$($orgUpdateReplay.Body.outcome)"
    $relink=Call 'POST' "/contacts/$contactA/organization-relationships" (@{organizationId=$orgB;role='partner'}|ConvertTo-Json -Compress) 'idem-c6-org-relink' 9;Add-Result 'ended Organization pair can relink without deleting history' '200|2' "$($relink.Status)|$([string](Get-Scalar "SELECT COUNT(*) FROM contacts.OrganizationRelationships WHERE ContactId='$contactA' AND OrganizationId='$orgB'"))"
    Add-Result 'all C6 mutation event types have audit and outbox evidence' '6|6' ([string](Get-Scalar "SELECT CONCAT((SELECT COUNT(DISTINCT Operation) FROM contacts.AuditRecords WHERE AggregateId='$contactA' AND Operation IN ('createContactOrganizationRelationship','updateContactOrganizationRelationship','endContactOrganizationRelationship','createContactCustomerRelationship','updateContactCustomerRelationship','endContactCustomerRelationship')),'|',(SELECT COUNT(DISTINCT EventType) FROM contacts.OutboxMessages WHERE AggregateId='$contactA' AND EventType IN ('CONTACT_ORGANIZATION_RELATIONSHIP_CREATED','CONTACT_ORGANIZATION_RELATIONSHIP_UPDATED','CONTACT_ORGANIZATION_RELATIONSHIP_ENDED','CONTACT_CUSTOMER_RELATIONSHIP_CREATED','CONTACT_CUSTOMER_RELATIONSHIP_UPDATED','CONTACT_CUSTOMER_RELATIONSHIP_ENDED')))"))
    Add-Result 'exact replays add no duplicate audit or outbox for any C6 operation' '3|1|1|3|1|1|3|1|1|3|1|1' ([string](Get-Scalar "SELECT CONCAT((SELECT COUNT(*) FROM contacts.AuditRecords WHERE AggregateId='$contactA' AND Operation='createContactOrganizationRelationship'),'|',(SELECT COUNT(*) FROM contacts.AuditRecords WHERE AggregateId='$contactA' AND Operation='updateContactOrganizationRelationship'),'|',(SELECT COUNT(*) FROM contacts.AuditRecords WHERE AggregateId='$contactA' AND Operation='endContactOrganizationRelationship'),'|',(SELECT COUNT(*) FROM contacts.AuditRecords WHERE AggregateId='$contactA' AND Operation='createContactCustomerRelationship'),'|',(SELECT COUNT(*) FROM contacts.AuditRecords WHERE AggregateId='$contactA' AND Operation='updateContactCustomerRelationship'),'|',(SELECT COUNT(*) FROM contacts.AuditRecords WHERE AggregateId='$contactA' AND Operation='endContactCustomerRelationship'),'|',(SELECT COUNT(*) FROM contacts.OutboxMessages WHERE AggregateId='$contactA' AND EventType='CONTACT_ORGANIZATION_RELATIONSHIP_CREATED'),'|',(SELECT COUNT(*) FROM contacts.OutboxMessages WHERE AggregateId='$contactA' AND EventType='CONTACT_ORGANIZATION_RELATIONSHIP_UPDATED'),'|',(SELECT COUNT(*) FROM contacts.OutboxMessages WHERE AggregateId='$contactA' AND EventType='CONTACT_ORGANIZATION_RELATIONSHIP_ENDED'),'|',(SELECT COUNT(*) FROM contacts.OutboxMessages WHERE AggregateId='$contactA' AND EventType='CONTACT_CUSTOMER_RELATIONSHIP_CREATED'),'|',(SELECT COUNT(*) FROM contacts.OutboxMessages WHERE AggregateId='$contactA' AND EventType='CONTACT_CUSTOMER_RELATIONSHIP_UPDATED'),'|',(SELECT COUNT(*) FROM contacts.OutboxMessages WHERE AggregateId='$contactA' AND EventType='CONTACT_CUSTOMER_RELATIONSHIP_ENDED'))"))
    Add-Result 'target-owner label disclosures create read-audit evidence' 'True' ([string]([int](Get-Scalar "SELECT (SELECT COUNT(*) FROM organizations.ReadAuditRecords WHERE Operation='resolveContactOrganizationRelationshipTarget') + (SELECT COUNT(*) FROM customers.ReadAuditRecords WHERE Operation='resolveContactCustomerRelationshipTarget')") -gt 0))
    $archive=Call 'POST' "/contacts/$contactA/archive" '{}' 'idem-c6-archive' 10;Add-Result 'Contact archived through authoritative API' '200|11' "$($archive.Status)|$($archive.Body.version)";$archivedSummary=Call 'GET' "/contacts/$contactA/relationship-summary";Add-Result 'archived Contact retains relationship history read' '200|3|3|0' "$($archivedSummary.Status)|$($archivedSummary.Body.organizationRelationships.Count)|$($archivedSummary.Body.customerRelationships.Count)|$($archivedSummary.Body.allowedActions.Count)";$before=Effects $contactA
    foreach($probe in @(@('POST',"/contacts/$contactA/customer-relationships",'{"customerId":"customer_c6_b","role":"support"}','idem-c6-arch-create'),@('PATCH',"/contacts/$contactA/customer-relationships/$custRelA",'{"role":"technical"}','idem-c6-arch-update'),@('POST',"/contacts/$contactA/customer-relationships/$custRelA/end",'{"endedReason":"blocked"}','idem-c6-arch-end'))){$x=Call $probe[0] $probe[1] $probe[2] $probe[3] 11;Add-Result "archived Contact $($probe[0]) mutation rejected" '409|CONTACT_ALREADY_ARCHIVED' "$($x.Status)|$($x.Body.code)"};Add-Result 'archived mutation attempts have zero effects' $before (Effects $contactA)
    foreach($probe in @(@('POST',"/contacts/$contactA/organization-relationships",'{"organizationId":"organization_c6_a","role":"employee"}','idem-c6-arch-org-create'),@('PATCH',"/contacts/$contactA/organization-relationships/$orgRelA",'{"role":"technical"}','idem-c6-arch-org-update'),@('POST',"/contacts/$contactA/organization-relationships/$orgRelA/end",'{"endedReason":"blocked"}','idem-c6-arch-org-end'))){$x=Call $probe[0] $probe[1] $probe[2] $probe[3] 11;Add-Result "archived Contact Organization $($probe[0]) mutation rejected" '409|CONTACT_ALREADY_ARCHIVED' "$($x.Status)|$($x.Body.code)"};Add-Result 'archived Organization mutation attempts have zero effects' $before (Effects $contactA)
    Invoke-SqlNonQuery "DELETE access.RoleCapabilities WHERE RoleId='$roleId' AND Capability='organizations.read'";$redacted=Call 'GET' "/contacts/$contactA/relationship-summary";Add-Result 'summary omits unauthorized Organization identities' '0|False' "$($redacted.Body.organizationRelationships.Count)|$($redacted.Raw -match 'C6 Organization')";Invoke-SqlNonQuery "INSERT access.RoleCapabilities(RoleId,Capability) VALUES('$roleId','organizations.read');DELETE access.RoleCapabilities WHERE RoleId='$roleId' AND Capability='customers.view'";$redactedCustomer=Call 'GET' "/contacts/$contactA/relationship-summary";Add-Result 'summary omits unauthorized Customer identities' '0|False' "$($redactedCustomer.Body.customerRelationships.Count)|$($redactedCustomer.Raw -match 'CUS-C6')"
} finally {
    if($null-ne$hostProcess-and-not$hostProcess.HasExited){Stop-Process -Id $hostProcess.Id -Force;$hostProcess.WaitForExit(10000)|Out-Null}
    Push-Location $root;try{& dotnet ef migrations has-pending-model-changes --project $crmProject --context ContactsDbContext --no-build|Out-Null;Add-Result 'no pending Contacts EF model changes' '0' ([string]$LASTEXITCODE)}finally{Pop-Location}
    if(-not$KeepDatabase){try{Invoke-SqlNonQuery "IF DB_ID('$DatabaseName') IS NOT NULL BEGIN ALTER DATABASE [$DatabaseName] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [$DatabaseName]; END;" 'master'}catch{}}
}
$script:Results|ForEach-Object{Write-Host $_};Write-Host "Contact Relationships C6 verification: passed=$($script:Passed) failed=$($script:Failed)";if($script:Failed-ne 0){throw 'Contact Relationships C6 verification failed.'};Write-Host 'CONTACT RELATIONSHIPS C6: PASS'
