<# .SYNOPSIS Verifies the Payments-owned Payment Record read core against an isolated database and real ApiHost. #>
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)][ValidatePattern('^[A-Za-z0-9_]{1,128}$')][string]$DatabaseName,
    [string]$SqlServer='(localdb)\MSSQLLocalDB',[int]$Port=5359,[int]$ReadyTimeoutSeconds=420,[switch]$KeepDatabase)
$ErrorActionPreference='Stop'; Add-Type -AssemblyName System.Net.Http
$script:Passed=0;$script:Failed=0;$script:Results=New-Object System.Collections.ArrayList;$script:Counter=0
$script:BaseUrl="http://127.0.0.1:$Port";$script:Token=$null;$script:WorkspaceId=$null
function Add-Result([string]$Name,[string]$Expected,[string]$Actual){if($Expected-eq$Actual){$script:Passed++;[void]$script:Results.Add("PASS | $Name | $Actual")}else{$script:Failed++;[void]$script:Results.Add("FAIL | $Name | expected=$Expected actual=$Actual")}}
function New-ConnectionString([string]$Database){"Server=$SqlServer;Database=$Database;Trusted_Connection=True;TrustServerCertificate=True;MultipleActiveResultSets=True"}
function Invoke-SqlNonQuery([string]$Query,[string]$Database='master'){$c=New-Object System.Data.SqlClient.SqlConnection (New-ConnectionString $Database);$cmd=$null;$c.Open();try{$cmd=$c.CreateCommand();$cmd.CommandText=$Query;$cmd.CommandTimeout=120;[void]$cmd.ExecuteNonQuery()}finally{if($cmd){$cmd.Dispose()};$c.Dispose()}}
function Get-Scalar([string]$Query,[string]$Database){$c=New-Object System.Data.SqlClient.SqlConnection (New-ConnectionString $Database);$cmd=$null;$c.Open();try{$cmd=$c.CreateCommand();$cmd.CommandText=$Query;$cmd.CommandTimeout=120;return $cmd.ExecuteScalar()}finally{if($cmd){$cmd.Dispose()};$c.Dispose()}}
function New-RequestId{$script:Counter++;'req-payment-record-{0:d6}'-f$script:Counter}
function Invoke-Api{param([string]$Method,[string]$Path,[string]$Body,[string]$Token,[string]$WorkspaceId,[string]$IdempotencyKey)
    $req=New-Object System.Net.Http.HttpRequestMessage ([System.Net.Http.HttpMethod]::new($Method),"$script:BaseUrl$Path");[void]$req.Headers.TryAddWithoutValidation('X-Request-Id',(New-RequestId));[void]$req.Headers.TryAddWithoutValidation('X-Correlation-Id','corr-payment-record-read-0001')
    if($Token){[void]$req.Headers.TryAddWithoutValidation('Authorization',"Bearer $Token")};if($WorkspaceId){[void]$req.Headers.TryAddWithoutValidation('X-Workspace-Id',$WorkspaceId)};if($IdempotencyKey){[void]$req.Headers.TryAddWithoutValidation('Idempotency-Key',$IdempotencyKey)};if($Body){$req.Content=New-Object System.Net.Http.StringContent($Body,[Text.Encoding]::UTF8,'application/json')}
    $h=New-Object System.Net.Http.HttpClientHandler;$h.UseProxy=$false;$h.AllowAutoRedirect=$false;$client=New-Object System.Net.Http.HttpClient($h,$true);$client.Timeout=[TimeSpan]::FromSeconds(60);$resp=$null
    try{$resp=$client.SendAsync($req).GetAwaiter().GetResult();$raw=$resp.Content.ReadAsStringAsync().GetAwaiter().GetResult();$status=[int]$resp.StatusCode}finally{if($resp){$resp.Dispose()};$client.Dispose();$req.Dispose()};$payload=$null;if($raw){try{$payload=$raw|ConvertFrom-Json}catch{}};[pscustomobject]@{Status=$status;Body=$payload;Raw=$raw}}
function Invoke-Record([string]$Path){Invoke-Api -Method GET -Path $Path -Token $script:Token -WorkspaceId $script:WorkspaceId}
function Set-Scope([string]$RoleId,[string]$Scope){Invoke-SqlNonQuery -Database $DatabaseName -Query "DELETE FROM access.RoleDataScopes WHERE PolicyId='scope_payment_record_read'; INSERT INTO access.RoleDataScopes(PolicyId,RoleId,ResourceKey,Scope,AllowedOwnerIdsJson) VALUES('scope_payment_record_read','$RoleId','payments','$Scope','[]');"}
function Clear-Fields{Invoke-SqlNonQuery -Database $DatabaseName -Query "DELETE FROM access.RoleFieldSecurity WHERE PolicyId LIKE 'field_payment_record_%'"}
$root=(Resolve-Path(Join-Path $PSScriptRoot '..')).Path;$hostProject=Join-Path $root 'src/UnicoreCRM.ApiHost/UnicoreCRM.ApiHost.csproj';$paymentsRoot=Join-Path $root 'src/UnicoreCRM.Billing/Payments'
$email='payment.record.read@example.test';$password='Payment-Record-Read!2026';$hostProcess=$null;$logPath=Join-Path([IO.Path]::GetTempPath())("unicore-payment-record-$([Guid]::NewGuid().ToString('N')).log")
$recordA='payment_record_read_a';$recordB='payment_record_read_b';$recordForeign='payment_record_read_foreign';$buyerA='contact_record_a';$buyerB='organization_record_b';$foreignWorkspace='ws_payment_record_foreign'
try{
    Invoke-SqlNonQuery -Query "IF DB_ID('$DatabaseName') IS NOT NULL BEGIN ALTER DATABASE [$DatabaseName] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [$DatabaseName]; END; CREATE DATABASE [$DatabaseName];"
    $env:ASPNETCORE_ENVIRONMENT='Development';$env:DOTNET_ENVIRONMENT='Development';$env:ASPNETCORE_URLS=$script:BaseUrl;$env:ConnectionStrings__UnicoreCRM=New-ConnectionString $DatabaseName;$env:Development__ApplyMigrations='true';$env:UNICORE_DEV_SEED_ENABLED='false';$env:IdentityAuth__EmailVerification__Sender__Kind='DevelopmentLog';$env:IdentityAuth__DevelopmentBootstrap__Enabled='true';$env:IdentityAuth__DevelopmentBootstrap__Email=$email;$env:IdentityAuth__DevelopmentBootstrap__Password=$password;$env:IdentityAuth__DevelopmentBootstrap__DisplayName='Payment Record Fixture';$env:Workspace__DevelopmentBootstrap__Enabled='false';$env:AccessControl__DevelopmentBootstrap__Enabled='false';$env:Workflows__InitialWorkspaceProvisioning__ResumeEnabled='false';$env:AI__Provider__Kind='DevelopmentDeterministic'
    $hostProcess=Start-Process dotnet -ArgumentList @('run','--no-build','--no-launch-profile','--project',$hostProject)-PassThru -WindowStyle Hidden -RedirectStandardOutput $logPath -RedirectStandardError "$logPath.err";$ready=$false
    for($i=0;$i-lt$ReadyTimeoutSeconds;$i++){Start-Sleep -Seconds 1;if($hostProcess.HasExited){throw "ApiHost exited $($hostProcess.ExitCode). See $logPath"};try{if((Invoke-Api -Method GET -Path '/auth/session').Status-gt 0){$ready=$true;break}}catch{}};if(-not$ready){throw "ApiHost not ready. See $logPath"}
    Add-Result 'unauthenticated list rejected' '401' ([string](Invoke-Api -Method GET -Path '/payments' -WorkspaceId 'ws_unknown').Status);Add-Result 'unauthenticated detail rejected' '401' ([string](Invoke-Api -Method GET -Path "/payments/$recordA/detail" -WorkspaceId 'ws_unknown').Status)
    $signIn=Invoke-Api -Method POST -Path '/auth/sessions' -IdempotencyKey 'idem-payment-record-signin-0001' -Body(@{email=$email;password=$password}|ConvertTo-Json -Compress);if($signIn.Status-ne 200){throw "Sign-in failed: $($signIn.Raw)"};$script:Token=$signIn.Body.accessToken
    $provision=Invoke-Api -Method POST -Path '/workspaces/initial-provisioning' -Token $script:Token -IdempotencyKey 'idem-payment-record-provision-0001' -Body '{"name":"Payment Record Workspace"}';Add-Result 'Workspace provisioning succeeds' '201' ([string]$provision.Status);$script:WorkspaceId=$provision.Body.workspaceId
    $roleId=Get-Scalar -Database $DatabaseName -Query "SELECT RoleId FROM access.Roles WHERE WorkspaceId='$($script:WorkspaceId)' AND Name='Workspace Owner'";Invoke-SqlNonQuery -Database $DatabaseName -Query "INSERT INTO access.RoleCapabilities(RoleId,Capability)VALUES('$roleId','payments.read')"
    Add-Result 'fresh migration creates PaymentRecords' '1' ([string](Get-Scalar -Database $DatabaseName -Query "SELECT COUNT(*) FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA='payments' AND TABLE_NAME='PaymentRecords'"));Add-Result 'buyer filter index exists' '1' ([string](Get-Scalar -Database $DatabaseName -Query "SELECT COUNT(*) FROM sys.indexes WHERE object_id=OBJECT_ID('payments.PaymentRecords') AND name='IX_PaymentRecords_WorkspaceId_BuyerId'"))
    Invoke-SqlNonQuery -Database $DatabaseName -Query @"
INSERT INTO payments.PaymentRecords(WorkspaceId,PaymentRecordId,BuyerType,BuyerId,OrderId,PaymentIntentId,Kind,State,Amount,Currency,MethodCode,Channel,ProviderCode,RefundOfPaymentRecordId,RefundOfCustomerCreditId,RefundIntentId,OccurredAt,ExternalReference,EvidenceJson,ReconciliationState,CodCustomerCollectionState,CodMerchantRemittanceState,EffectiveForReceivables,ResourceVersion,CreatedAt,UpdatedAt,AllocationsJson,RefundsJson,CustomerCreditsJson,UnallocatedAmount,UnallocatedCurrency,RefundableAmount,RefundableCurrency) VALUES
('$($script:WorkspaceId)','$recordA','CONTACT','$buyerA','order_record_a','payment_intent_read_a','PAYMENT','SUCCEEDED',150.250000,'USD','CARD','ONLINE_GATEWAY','provider_alpha',NULL,NULL,NULL,'2026-08-30T10:00:00+00:00','external-a',N'[{"id":"evidence_a","type":"PAYMENT_PROOF","fileName":"proof.pdf","mimeType":"application/pdf","url":"/evidence/a","externalReference":"provider-proof-a","capturedAt":"2026-08-30T10:01:00Z","capturedBy":"member_a","verificationState":"VERIFIED","notes":"verified","lockedByBusinessEvent":true,"createdAt":"2026-08-30T10:02:00Z"}]','MATCHED','COLLECTED','REMITTED',1,7,'2026-08-30T10:00:00+00:00','2026-08-30T11:00:00+00:00',N'[{"id":"allocation_a","workspaceId":"$($script:WorkspaceId)","buyerRef":{"type":"CONTACT","id":"$buyerA"},"invoiceId":"invoice_a","sourceType":"PAYMENT_RECORD","sourceId":"$recordA","scheduleLineId":"schedule_a","amount":{"amount":"100.25","currency":"USD"},"state":"EFFECTIVE","resourceVersion":2,"createdAt":"2026-08-30T10:05:00Z","auditEvidenceIds":["audit_a"]}]',N'[{"id":"refund_a","workspaceId":"$($script:WorkspaceId)","sourceReturnId":"return_a","buyerRef":{"type":"CONTACT","id":"$buyerA"},"orderId":"order_record_a","invoiceIds":["invoice_a"],"source":{"type":"PAYMENT_RECORD","id":"$recordA"},"amount":{"amount":"10","currency":"USD"},"state":"PROCESSING","reasonCode":"CUSTOMER_REQUEST","reason":"Customer requested refund","resourceVersion":1,"createdAt":"2026-08-30T10:06:00Z","updatedAt":"2026-08-30T10:07:00Z","providerCode":"provider_alpha","latestProviderAttemptId":"attempt_a"}]',N'[{"id":"credit_a","workspaceId":"$($script:WorkspaceId)","buyerRef":{"type":"CONTACT","id":"$buyerA"},"sourcePaymentRecordId":"$recordA","originalAmount":{"amount":"20","currency":"USD"},"availableAmount":{"amount":"15","currency":"USD"},"state":"PARTIALLY_ALLOCATED","resourceVersion":3,"createdAt":"2026-08-30T10:08:00Z","updatedAt":"2026-08-30T10:09:00Z"}]',50.000000,'USD',40.000000,'USD'),
('$($script:WorkspaceId)','$recordB','ORGANIZATION_ACCOUNT','$buyerB',NULL,NULL,'PAYMENT','PENDING',99.000000,'EUR','BANK_TRANSFER','BANK',NULL,NULL,NULL,NULL,'2026-08-29T00:00:00+00:00',NULL,NULL,'UNRECONCILED',NULL,NULL,0,0,'2026-08-29T00:00:00+00:00','2026-08-29T00:00:00+00:00',N'[]',N'[]',N'[]',99.000000,'EUR',99.000000,'EUR'),
('$foreignWorkspace','$recordForeign','CONTACT','$buyerA',NULL,NULL,'PAYMENT','FAILED',999.000000,'USD','SECRET','EXTERNAL','secret_provider',NULL,NULL,NULL,'2026-08-29T00:00:00+00:00','foreign-secret',NULL,'MISMATCH',NULL,NULL,0,1,'2026-08-29T00:00:00+00:00','2026-08-29T00:00:00+00:00',N'[]',N'[]',N'[]',999.000000,'USD',999.000000,'USD');
"@
    Set-Scope $roleId 'Workspace';$list=Invoke-Record '/payments';$detail=Invoke-Record "/payments/$recordA/detail"
    Add-Result 'WORKSPACE list succeeds' '200' ([string]$list.Status);Add-Result 'Workspace list count' '2' ([string]$list.Body.Count);Add-Result 'detail succeeds' '200' ([string]$detail.Status);Add-Result 'foreign record excluded' 'False' ([string]($list.Body.id-contains$recordForeign));Add-Result 'foreign values never emitted' 'True' ([string](($list.Raw-notmatch'foreign-secret|secret_provider')-and($detail.Raw-notmatch'foreign-secret|secret_provider')))
    $filtered=Invoke-Record "/payments?buyerId=$buyerA";Add-Result 'buyerId exact filter count' '1' ([string]$filtered.Body.Count);Add-Result 'buyerId exact identity' $recordA $filtered.Body.id;Add-Result 'unknown buyer filter empty' '0' ([string](Invoke-Record '/payments?buyerId=buyer_unknown').Body.Count)
    Add-Result 'malformed buyer rejected' '422' ([string](Invoke-Record '/payments?buyerId=%20bad').Status);Add-Result 'empty buyer rejected' '422' ([string](Invoke-Record '/payments?buyerId=').Status);Add-Result 'malformed detail nondisclosing' '404' ([string](Invoke-Record '/payments/%20bad/detail').Status);Add-Result 'unknown detail nondisclosing' '404' ([string](Invoke-Record '/payments/payment_record_unknown/detail').Status);Add-Result 'foreign detail nondisclosing' '404' ([string](Invoke-Record "/payments/$recordForeign/detail").Status)
    $recordDoc=$detail.Body.record;Add-Result 'detail exact shape' 'allocations,customerCredits,record,refundableAmount,refunds,unallocatedAmount' (($detail.Body.PSObject.Properties.Name|Sort-Object)-join',');Add-Result 'record exact full shape' 'amount,buyerRef,channel,codCustomerCollectionState,codMerchantRemittanceState,createdAt,effectiveForReceivables,evidence,externalReference,id,intentId,kind,methodCode,occurredAt,orderId,providerCode,reconciliationState,resourceVersion,state,updatedAt,workspaceId' (($recordDoc.PSObject.Properties.Name|Sort-Object)-join',')
    $minimal=@($list.Body|Where-Object id -eq $recordB)[0];Add-Result 'optional record fields omitted' 'amount,buyerRef,channel,createdAt,effectiveForReceivables,id,kind,methodCode,occurredAt,reconciliationState,resourceVersion,state,updatedAt,workspaceId' (($minimal.PSObject.Properties.Name|Sort-Object)-join',')
    Add-Result 'record enums money and version exact' 'PAYMENT|SUCCEEDED|MATCHED|150.25|USD|7' "$($recordDoc.kind)|$($recordDoc.state)|$($recordDoc.reconciliationState)|$($recordDoc.amount.amount)|$($recordDoc.amount.currency)|$($recordDoc.resourceVersion)";Add-Result 'detail nested documents projected' '1|1|1|50|40' "$($detail.Body.allocations.Count)|$($detail.Body.refunds.Count)|$($detail.Body.customerCredits.Count)|$($detail.Body.unallocatedAmount.amount)|$($detail.Body.refundableAmount.amount)";Add-Result 'UTC timestamps emitted' 'True' ([string]($detail.Raw-match'"occurredAt":"[^"]+Z"'))
    Invoke-SqlNonQuery -Database $DatabaseName -Query "DELETE FROM access.RoleCapabilities WHERE RoleId='$roleId' AND Capability='payments.read'";Add-Result 'missing capability denies list' '403' ([string](Invoke-Record '/payments').Status);Add-Result 'missing capability denies detail' '403' ([string](Invoke-Record "/payments/$recordA/detail").Status);Add-Result 'capability denial precedes malformed buyer' '403' ([string](Invoke-Record '/payments?buyerId=%20bad').Status);Add-Result 'capability denial precedes empty buyer' '403' ([string](Invoke-Record '/payments?buyerId=').Status);Add-Result 'capability denial precedes malformed path' '403' ([string](Invoke-Record '/payments/%20bad/detail').Status);Invoke-SqlNonQuery -Database $DatabaseName -Query "INSERT INTO access.RoleCapabilities(RoleId,Capability)VALUES('$roleId','payments.read')"
    foreach($scope in @('Own','Team','Custom')){Set-Scope $roleId $scope;Add-Result "$($scope.ToUpperInvariant()) list fails closed" '0' ([string](Invoke-Record '/payments').Body.Count);Add-Result "$($scope.ToUpperInvariant()) detail fails closed" '404' ([string](Invoke-Record "/payments/$recordA/detail").Status)}
    Set-Scope $roleId 'Workspace';Clear-Fields;Invoke-SqlNonQuery -Database $DatabaseName -Query "INSERT INTO access.RoleFieldSecurity(PolicyId,RoleId,ResourceKey,FieldKey,Access)VALUES('field_payment_record_kind','$roleId','payments','kind','Hidden')";Add-Result 'required record field fails list closed' '403' ([string](Invoke-Record '/payments').Status);Add-Result 'required record field fails detail closed' '403' ([string](Invoke-Record "/payments/$recordA/detail").Status);Clear-Fields
    Invoke-SqlNonQuery -Database $DatabaseName -Query "INSERT INTO access.RoleFieldSecurity(PolicyId,RoleId,ResourceKey,FieldKey,Access)VALUES('field_payment_record_allocations','$roleId','payments','allocations','Hidden')";Add-Result 'detail-only required field does not deny list' '200' ([string](Invoke-Record '/payments').Status);Add-Result 'detail-only required field fails detail closed' '403' ([string](Invoke-Record "/payments/$recordA/detail").Status);Clear-Fields
    Invoke-SqlNonQuery -Database $DatabaseName -Query "INSERT INTO access.RoleFieldSecurity(PolicyId,RoleId,ResourceKey,FieldKey,Access)VALUES('field_payment_record_provider','$roleId','payments','providerCode','Hidden')";Add-Result 'optional provider omitted from list' 'True' ([string]((Invoke-Record '/payments').Raw-notmatch'providerCode'));$providerHiddenDetail=Invoke-Record "/payments/$recordA/detail";Add-Result 'optional provider omitted from detail record' 'False' ([string]($providerHiddenDetail.Body.record.PSObject.Properties.Name-contains'providerCode'));Clear-Fields
    Invoke-SqlNonQuery -Database $DatabaseName -Query "INSERT INTO access.RoleFieldSecurity(PolicyId,RoleId,ResourceKey,FieldKey,Access)VALUES('field_payment_record_plan_only','$roleId','payments','planId','Hidden')";Add-Result 'unrelated representation field does not affect records' '200' ([string](Invoke-Record '/payments').Status);Clear-Fields
    Add-Result 'missing Trusted Workspace rejected' '403' ([string](Invoke-Api -Method GET -Path '/payments' -Token $script:Token).Status)
    Invoke-SqlNonQuery -Database $DatabaseName -Query "UPDATE payments.PaymentRecords SET AllocationsJson=N'{`"not`":`"array`"}' WHERE WorkspaceId='$($script:WorkspaceId)' AND PaymentRecordId='$recordA'";Add-Result 'corrupt detail document fails detail closed' '500' ([string](Invoke-Record "/payments/$recordA/detail").Status);Add-Result 'detail-only corruption does not invalidate list representation' '200' ([string](Invoke-Record '/payments').Status);Invoke-SqlNonQuery -Database $DatabaseName -Query "UPDATE payments.PaymentRecords SET AllocationsJson=N'[]',EvidenceJson=N'[{`"id`":`"evidence_a`"}]' WHERE WorkspaceId='$($script:WorkspaceId)' AND PaymentRecordId='$recordA'";Add-Result 'corrupt record evidence fails list closed' '500' ([string](Invoke-Record '/payments').Status);$badDetail=Invoke-Record "/payments/$recordA/detail";Add-Result 'corrupt record evidence fails detail closed' '500' ([string]$badDetail.Status);Add-Result 'corrupt detail emits no partial record' 'True' ([string]($badDetail.Raw-notmatch$recordA))
    foreach($case in @(@('POST','/payments'),@('PATCH',"/payments/$recordA"),@('DELETE',"/payments/$recordA"),@('POST',"/payments/$recordA/capture"))){Add-Result "no mutation $($case[0]) $($case[1])" 'True' ([string]((Invoke-Api -Method $case[0] -Path $case[1] -Token $script:Token -WorkspaceId $script:WorkspaceId -Body '{}').Status-in 404,405))}
    $files=Get-ChildItem $paymentsRoot -Recurse -File|Where-Object Extension -in '.cs','.csproj';$source=($files|ForEach-Object{Get-Content $_.FullName -Raw})-join"`n";Add-Result 'no foreign DbContext' 'True' ([string]($source-notmatch'OrdersDbContext|InvoicesDbContext|QuotesDbContext|CustomersDbContext|ShippingDbContext|FulfillmentDbContext'));Add-Result 'no provider runtime client' 'True' ([string]($source-notmatch'HttpClient|ProviderClient|IPaymentProvider|Webhook'));Add-Result 'no mutation workflow outbox idempotency' 'True' ([string]($source-notmatch'MapPost|MapPatch|MapDelete|IWorkflow|Outbox|Idempotenc'))
    $routes=Get-Content(Join-Path $paymentsRoot 'Contracts/PaymentRecordEndpoints.cs')-Raw;Add-Result 'exactly two Payment Record GET routes' '2' ([string]([regex]::Matches($routes,'\.MapGet\(').Count));$persistence=Get-Content(Join-Path $paymentsRoot 'Infrastructure/Persistence/EfPaymentsPersistence.cs')-Raw;Add-Result 'no invented Payment Record ordering pagination' 'True' ([string]($persistence-notmatch'PaymentRecords[\s\S]{0,500}(OrderBy|Skip|Take)'))
}catch{$script:Failed++;[void]$script:Results.Add("FAIL | verifier execution | $($_.Exception.Message)");if(Test-Path $logPath){[void]$script:Results.Add((Get-Content $logPath -Tail 40)-join"`n")}}
finally{if($hostProcess -and -not $hostProcess.HasExited){Stop-Process -Id $hostProcess.Id -Force;$hostProcess.WaitForExit()};if(-not $KeepDatabase){try{Invoke-SqlNonQuery -Query "IF DB_ID('$DatabaseName') IS NOT NULL BEGIN ALTER DATABASE [$DatabaseName] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [$DatabaseName]; END;"}catch{}};Remove-Item Env:ConnectionStrings__UnicoreCRM -ErrorAction SilentlyContinue}
$script:Results|ForEach-Object{Write-Host $_};Write-Host "PAYMENT RECORD READ CORE RESULT: PASS=$script:Passed FAIL=$script:Failed";if($script:Failed -gt 0){exit 1}
