param([Parameter(Mandatory=$true)][string]$DatabaseName)
$ErrorActionPreference='Stop'; Add-Type -AssemblyName System.Net.Http
$server='(localdb)\MSSQLLocalDB'; $connection="Server=$server;Database=$DatabaseName;Trusted_Connection=True;MultipleActiveResultSets=true;TrustServerCertificate=True"; $url='http://127.0.0.1:5091'
$email='outbound.owner@example.test';$password='Outbound-Smoke!234';$jwt=[guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N');$pepper=[guid]::NewGuid().ToString('N')+[guid]::NewGuid().ToString('N')
$dll=(Resolve-Path "$PSScriptRoot/../src/UnicoreCRM.ApiHost/bin/Debug/net10.0/UnicoreCRM.ApiHost.dll").Path;$root=(Resolve-Path "$PSScriptRoot/../src/UnicoreCRM.ApiHost").Path;$tmp=New-Item -ItemType Directory -Path ([IO.Path]::Combine([IO.Path]::GetTempPath(),'unicore-outbound-'+[guid]::NewGuid().ToString('N')))
function Env {
 $env:ASPNETCORE_ENVIRONMENT='Development';$env:DOTNET_ENVIRONMENT='Development';$env:ASPNETCORE_URLS=$url;$env:ConnectionStrings__UnicoreCRM=$connection;$env:IdentityAuth__Jwt__SigningKey=$jwt;$env:IdentityAuth__RefreshTokenPepper=$pepper
 $env:IdentityAuth__DevelopmentBootstrap__Enabled='true';$env:IdentityAuth__DevelopmentBootstrap__ApplyMigrations='false';$env:IdentityAuth__DevelopmentBootstrap__Email=$email;$env:IdentityAuth__DevelopmentBootstrap__Password=$password;$env:IdentityAuth__DevelopmentBootstrap__DisplayName='Outbound Owner'
 $env:Workspace__DevelopmentBootstrap__Enabled='true';$env:Workspace__DevelopmentBootstrap__ApplyMigrations='false';$env:Workspace__DevelopmentBootstrap__IdentityEmail=$email;$env:Workspace__DevelopmentBootstrap__MemberWorkspace__Key='outbound-main';$env:Workspace__DevelopmentBootstrap__MemberWorkspace__Name='Outbound Main';$env:Workspace__DevelopmentBootstrap__MemberWorkspace__LogoText='OM';$env:Workspace__DevelopmentBootstrap__MemberWorkspace__Locale='en';$env:Workspace__DevelopmentBootstrap__MemberWorkspace__TimeZone='UTC';$env:Workspace__DevelopmentBootstrap__MemberWorkspace__BaseCurrency='USD';$env:Workspace__DevelopmentBootstrap__MemberWorkspace__AvailableProductSpaces__0='crm'
 $env:Workspace__DevelopmentBootstrap__NonMemberWorkspace__Key='outbound-foreign';$env:Workspace__DevelopmentBootstrap__NonMemberWorkspace__Name='Outbound Foreign';$env:Workspace__DevelopmentBootstrap__NonMemberWorkspace__LogoText='OF';$env:Workspace__DevelopmentBootstrap__NonMemberWorkspace__Locale='en';$env:Workspace__DevelopmentBootstrap__NonMemberWorkspace__TimeZone='UTC';$env:Workspace__DevelopmentBootstrap__NonMemberWorkspace__BaseCurrency='USD';$env:Workspace__DevelopmentBootstrap__NonMemberWorkspace__AvailableProductSpaces__0='crm'
 $env:AccessControl__DevelopmentBootstrap__Enabled='true';$env:AccessControl__DevelopmentBootstrap__ApplyMigrations='false';$env:AccessControl__DevelopmentBootstrap__IdentityEmail=$email;$env:AccessControl__DevelopmentBootstrap__WorkspaceKey='outbound-main';$env:AccessControl__DevelopmentBootstrap__RoleName='Outbound Owner';$env:AccessControl__DevelopmentBootstrap__Capabilities__0='workspace.context.resolve';$env:AccessControl__DevelopmentBootstrap__Capabilities__1='studio.read';$env:AccessControl__DevelopmentBootstrap__Capabilities__2='studio.configure';$env:AccessControl__DevelopmentBootstrap__Capabilities__3='contacts.read';$env:AccessControl__DevelopmentBootstrap__Capabilities__4='contacts.create'
}
function Send($method,$path,$body,$headers){$m=[Net.Http.HttpRequestMessage]::new([Net.Http.HttpMethod]::new($method),"$url$path");if($null-ne$body){$m.Content=[Net.Http.StringContent]::new(($body|ConvertTo-Json -Compress),[Text.Encoding]::UTF8,'application/json')};foreach($e in $headers.GetEnumerator()){$null=$m.Headers.TryAddWithoutValidation($e.Key,$e.Value)};$r=$client.SendAsync($m).GetAwaiter().GetResult();$text=$r.Content.ReadAsStringAsync().GetAwaiter().GetResult();$m.Dispose();[pscustomobject]@{Status=[int]$r.StatusCode;Body=$text;ETag=[string]$r.Headers.ETag}}
function NewMessage($method,$path,$body,$headers){$m=[Net.Http.HttpRequestMessage]::new([Net.Http.HttpMethod]::new($method),"$url$path");if($null-ne$body){$m.Content=[Net.Http.StringContent]::new(($body|ConvertTo-Json -Compress),[Text.Encoding]::UTF8,'application/json')};foreach($e in $headers.GetEnumerator()){$null=$m.Headers.TryAddWithoutValidation($e.Key,$e.Value)};return $m}
function Expect($r,$status,$name){if($r.Status-ne$status){throw "$name expected $status got $($r.Status): $($r.Body)"};Write-Output "OK: $name"}
& sqlcmd -S $server -d master -b -Q "IF DB_ID('$DatabaseName') IS NOT NULL BEGIN ALTER DATABASE [$DatabaseName] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; DROP DATABASE [$DatabaseName]; END; CREATE DATABASE [$DatabaseName];"|Out-Null
Env;& dotnet $dll --migrate|Out-Null;& dotnet $dll --seed-demo|Out-Null
$out=Join-Path $tmp 'host.out';$err=Join-Path $tmp 'host.err';$p=Start-Process dotnet -ArgumentList @($dll) -WorkingDirectory $root -WindowStyle Hidden -RedirectStandardOutput $out -RedirectStandardError $err -PassThru;$client=[Net.Http.HttpClient]::new();$client.Timeout=[TimeSpan]::FromSeconds(20)
try{
 for($i=0;$i-lt80;$i++){try{if((Send GET '/auth/session' $null @{}).Status-eq401){break}}catch{};Start-Sleep -Milliseconds 250}
 $login=Send POST '/auth/sessions' @{email=$email;password=$password;deviceLabel='Outbound verifier'} @{'Idempotency-Key'='idem-login-001';'X-Request-Id'='req-login-001';'X-Correlation-Id'='corr-login-001'};Expect $login 200 'authentication';$token=($login.Body|ConvertFrom-Json).accessToken
 $ws=(& sqlcmd -S $server -d $DatabaseName -h -1 -W -Q "SET NOCOUNT ON;SELECT WorkspaceId FROM workspace.Workspaces WHERE [Key]='outbound-main'"|?{$_.Trim()})-join'';$foreign=(& sqlcmd -S $server -d $DatabaseName -h -1 -W -Q "SET NOCOUNT ON;SELECT WorkspaceId FROM workspace.Workspaces WHERE [Key]='outbound-foreign'"|?{$_.Trim()})-join''
 $h=@{Authorization="Bearer $token";'X-Workspace-Id'=$ws;'X-Correlation-Id'='corr-outbound-001';'X-Request-Id'='request-outbound-001'}
 $role=((& sqlcmd -S $server -d $DatabaseName -h -1 -W -Q "SET NOCOUNT ON;SELECT RoleId FROM access.Roles WHERE WorkspaceId='$ws' AND Name='Outbound Owner'"|?{$_.Trim()})-join'').Trim()
 & sqlcmd -S $server -d $DatabaseName -b -Q "DELETE FROM access.RoleCapabilities WHERE RoleId='$role' AND Capability='studio.read'"|Out-Null;Expect (Send GET '/integration-event-catalog' $null $h) 403 'studio.read denial';& sqlcmd -S $server -d $DatabaseName -b -Q "INSERT access.RoleCapabilities(RoleId,Capability) VALUES('$role','studio.read')"|Out-Null
 Expect (Send GET '/integration-event-catalog' $null $h) 200 'catalog studio.read';Expect (Send POST '/outbound-webhooks' @{name='missing';eventType='crm.contact.changed';endpointUrl='https://example.com/hook'} $h) 400 'Idempotency-Key required'
 $contactHeaders=$h.Clone();$contactHeaders['Idempotency-Key']='idem-contact-event-001';$contact=Send POST '/contacts' @{fullName='Event relay HTTP contact';workEmail='event.relay@example.test'} $contactHeaders;Expect $contact 201 'public Contact mutation';$contactId=($contact.Body|ConvertFrom-Json).aggregateId
 $journalCount=0;for($i=0;$i-lt40;$i++){$journalCount=[int](((& sqlcmd -S $server -d $DatabaseName -h -1 -W -Q "SET NOCOUNT ON;SELECT COUNT(*) FROM ops.IntegrationEventJournal WHERE WorkspaceId='$ws' AND SubjectId='$contactId' AND EventType='crm.contact.changed'"|?{$_.Trim()})-join'').Trim());if($journalCount-eq1){break};Start-Sleep -Milliseconds 250};if($journalCount-ne1){throw 'HTTP Contact event did not traverse owner outbox and relay into journal'};Write-Output 'OK: HTTP -> owner outbox -> relay -> journal'
 & sqlcmd -S $server -d $DatabaseName -b -Q "DELETE FROM access.RoleCapabilities WHERE RoleId='$role' AND Capability='studio.configure'"|Out-Null;$denied=$h.Clone();$denied['Idempotency-Key']='idem-denied-001';Expect (Send POST '/outbound-webhooks' @{name='denied';eventType='crm.contact.changed';endpointUrl='https://example.com/hook'} $denied) 403 'studio.configure denial';& sqlcmd -S $server -d $DatabaseName -b -Q "INSERT access.RoleCapabilities(RoleId,Capability) VALUES('$role','studio.configure')"|Out-Null
 $raceHeaders=$h.Clone();$raceHeaders['Idempotency-Key']='idem-concurrent-create-001';$raceBody=@{name='Concurrent CRM events';eventType='crm.contact.changed';endpointUrl='https://example.com/concurrent'};$m1=NewMessage POST '/outbound-webhooks' $raceBody $raceHeaders;$m2=NewMessage POST '/outbound-webhooks' $raceBody $raceHeaders;$t1=$client.SendAsync($m1);$t2=$client.SendAsync($m2);[Threading.Tasks.Task]::WaitAll([Threading.Tasks.Task[]]@($t1,$t2));$r1=$t1.Result;$r2=$t2.Result;$b1=$r1.Content.ReadAsStringAsync().Result;$b2=$r2.Content.ReadAsStringAsync().Result;$statuses=@([int]$r1.StatusCode,[int]$r2.StatusCode)|Sort-Object;if(($statuses-join ',')-ne'200,201'){throw "concurrent create did not converge: $($statuses-join ',') $b1 $b2"};$raceId=(($b1|ConvertFrom-Json).subscription.subscriptionId);if(-not$raceId){$raceId=(($b2|ConvertFrom-Json).subscription.subscriptionId)};$raceSubscriptionCount=[int](((& sqlcmd -S $server -d $DatabaseName -h -1 -W -Q "SET NOCOUNT ON;SELECT COUNT(*) FROM integration.OutboundWebhookSubscriptions WHERE SubscriptionId='$raceId'"|?{$_.Trim()})-join'').Trim());$raceIdemCount=[int](((& sqlcmd -S $server -d $DatabaseName -h -1 -W -Q "SET NOCOUNT ON;SELECT COUNT(*) FROM integration.OutboundWebhookIdempotency WHERE IdempotencyKey='idem-concurrent-create-001'"|?{$_.Trim()})-join'').Trim());if($raceSubscriptionCount-ne1-or$raceIdemCount-ne1){throw 'concurrent create persisted duplicate business/idempotency rows'};if((($b1|ConvertFrom-Json).signingSecret)-and(($b2|ConvertFrom-Json).signingSecret)){throw 'concurrent replay redisplayed one-time secret'};Write-Output 'OK: concurrent same-key Create converges through HTTP'
 $raceMut=$h.Clone();$raceMut['Idempotency-Key']='idem-concurrent-activate-001';$raceMut['If-Match']='"0"';$a1=NewMessage POST "/outbound-webhooks/$raceId/activate" @{} $raceMut;$a2=NewMessage POST "/outbound-webhooks/$raceId/activate" @{} $raceMut;$at1=$client.SendAsync($a1);$at2=$client.SendAsync($a2);[Threading.Tasks.Task]::WaitAll([Threading.Tasks.Task[]]@($at1,$at2));$ar1=$at1.Result;$ar2=$at2.Result;if([int]$ar1.StatusCode-ne200-or[int]$ar2.StatusCode-ne200){throw "concurrent mutation did not replay: $([int]$ar1.StatusCode),$([int]$ar2.StatusCode)"};$raceState=(((& sqlcmd -S $server -d $DatabaseName -h -1 -W -Q "SET NOCOUNT ON;SELECT CONCAT(Status,'|',Version) FROM integration.OutboundWebhookSubscriptions WHERE SubscriptionId='$raceId'"|?{$_.Trim()})-join'').Trim());if($raceState-ne'ACTIVE|1'){throw "concurrent mutation applied more than once: $raceState"};$raceMut['If-Match']='"1"';Expect (Send POST "/outbound-webhooks/$raceId/activate" @{} $raceMut) 409 'same key/body changed ExpectedVersion conflicts';Write-Output 'OK: concurrent same-key versioned mutation converges through HTTP'
 $createHeaders=$h.Clone();$createHeaders['Idempotency-Key']='idem-create-001';$create=Send POST '/outbound-webhooks' @{name='CRM events';eventType='crm.contact.changed';endpointUrl='https://example.com/hook'} $createHeaders;Expect $create 201 'subscription create';$created=$create.Body|ConvertFrom-Json;$id=$created.subscription.subscriptionId;if([string]::IsNullOrWhiteSpace($created.signingSecret)){throw 'create secret missing'}
 $replay=Send POST '/outbound-webhooks' @{name='CRM events';eventType='crm.contact.changed';endpointUrl='https://example.com/hook'} $createHeaders;Expect $replay 200 'same-key replay';if(($replay.Body|ConvertFrom-Json).signingSecret){throw 'replay redisplayed secret'}
 Expect (Send POST '/outbound-webhooks' @{name='changed';eventType='crm.contact.changed';endpointUrl='https://example.com/hook'} $createHeaders) 409 'same-key changed request conflict'
 $get=Send GET "/outbound-webhooks/$id" $null $h;Expect $get 200 'subscription GET';if($get.Body-match'signingSecret'){throw 'GET exposed signing secret'}
 $list=Send GET '/outbound-webhooks' $null $h;Expect $list 200 'subscription list';if($list.Body-match'signingSecret'){throw 'list exposed signing secret'}
 $bad=$h.Clone();$bad['Idempotency-Key']='idem-active-bad';$bad['If-Match']='"99"';Expect (Send POST "/outbound-webhooks/$id/activate" @{} $bad) 409 'stale If-Match conflict'
 $mut=$h.Clone();$mut['Idempotency-Key']='idem-active-001';$mut['If-Match']='"0"';$active=Send POST "/outbound-webhooks/$id/activate" @{} $mut;Expect $active 200 'activate'
 $mut['Idempotency-Key']='idem-pause-001';$mut['If-Match']='"1"';Expect (Send POST "/outbound-webhooks/$id/pause" @{} $mut) 200 'pause';$mut['Idempotency-Key']='idem-resume-001';$mut['If-Match']='"2"';Expect (Send POST "/outbound-webhooks/$id/resume" @{} $mut) 200 'resume'
 $mut['Idempotency-Key']='idem-rotate-001';$mut['If-Match']='"3"';$rotate=Send POST "/outbound-webhooks/$id/rotate-secret" @{} $mut;Expect $rotate 200 'rotate secret';if([string]::IsNullOrWhiteSpace(($rotate.Body|ConvertFrom-Json).signingSecret)){throw 'rotate secret missing'}
 $triggerHeaders=$h.Clone();$triggerHeaders['Idempotency-Key']='idem-contact-event-trigger-002';Expect (Send POST '/contacts' @{fullName='Event relay delivery trigger';workEmail='event.delivery@example.test'} $triggerHeaders) 201 'delivery trigger Contact mutation'
 Expect (Send GET '/outbound-webhook-deliveries' $null $h) 200 'delivery history'
 $deadId='';for($i=0;$i-lt40;$i++){$deadId=(((& sqlcmd -S $server -d $DatabaseName -h -1 -W -Q "SET NOCOUNT ON;SELECT TOP 1 DeliveryId FROM integration.OutboundWebhookDeliveries WHERE SubscriptionId='$id'"|?{$_.Trim()})-join'').Trim());if(-not[string]::IsNullOrWhiteSpace($deadId)){break};Start-Sleep -Milliseconds 250};if([string]::IsNullOrWhiteSpace($deadId)){throw 'fan-out did not create a delivery for HTTP replay verification'};& sqlcmd -S $server -d $DatabaseName -b -Q "UPDATE integration.OutboundWebhookDeliveries SET Status='DEAD_LETTER',AttemptCount=6,DeadLetteredAt=SYSUTCDATETIME(),ExecutionAttemptId=NULL,LeaseExpiresAt=NULL WHERE DeliveryId='$deadId'"|Out-Null;$replayHeaders=$h.Clone();$replayHeaders['Idempotency-Key']='idem-dead-replay-001';Expect (Send POST "/outbound-webhook-deliveries/$deadId/replay" @{} $replayHeaders) 200 'dead-letter replay'
 $foreignHeaders=$h.Clone();$foreignHeaders['X-Workspace-Id']=$foreign;Expect (Send GET "/outbound-webhooks/$id" $null $foreignHeaders) 403 'foreign workspace anti-enumeration'
 $mut['Idempotency-Key']='idem-archive-001';$mut['If-Match']='"4"';Expect (Send POST "/outbound-webhooks/$id/archive" @{} $mut) 200 'archive'
 Write-Output 'Outbound webhook management HTTP verifier completed.'
}finally{if($p-and-not$p.HasExited){Stop-Process -Id $p.Id};$client.Dispose()}
