using System.Globalization;using Microsoft.AspNetCore.Builder;using Microsoft.AspNetCore.Http;using Microsoft.AspNetCore.Routing;using UnicoreCRM.Integrations.Webhooks.Outbound.Application;using UnicoreCRM.Platform.Workspace.Contracts;
namespace UnicoreCRM.Integrations.Webhooks.Outbound.Contracts;
public static class OutboundWebhookEndpoints{
 public static IEndpointRouteBuilder MapOutboundWebhookEndpoints(this IEndpointRouteBuilder e){MapGet(e,"/integration-event-catalog",async(HttpContext c,OutboundWebhookService s,CancellationToken ct)=>Result(c,await s.Catalog(Correlation(c),ct)),"getIntegrationEventCatalog");MapGet(e,"/outbound-webhooks",async(HttpContext c,OutboundWebhookService s,CancellationToken ct)=>Result(c,await s.List(Correlation(c),ct)),"listOutboundWebhookSubscriptions");MapGet(e,"/outbound-webhooks/{id}",async(string id,HttpContext c,OutboundWebhookService s,CancellationToken ct)=>Result(c,await s.Get(id,Correlation(c),ct)),"getOutboundWebhookSubscription");
 MapPost(e,"/outbound-webhooks",async(CreateOutboundWebhookSubscriptionRequest b,HttpContext c,OutboundWebhookService s,CancellationToken ct)=>TryCommand(c,false,out var m,out var error)?Result(c,await s.Create(b,m!,ct)):error!,"createOutboundWebhookSubscription");MapPut(e,"/outbound-webhooks/{id}",async(string id,UpdateOutboundWebhookSubscriptionRequest b,HttpContext c,OutboundWebhookService s,CancellationToken ct)=>TryCommand(c,true,out var m,out var error)?Result(c,await s.Update(id,b,m!,ct)):error!,"updateOutboundWebhookSubscription");
 foreach(var x in new[]{("activate","activateOutboundWebhookSubscription"),("pause","pauseOutboundWebhookSubscription"),("resume","resumeOutboundWebhookSubscription"),("archive","archiveOutboundWebhookSubscription"),("rotate-secret","rotateOutboundWebhookSecret")}){var action=x.Item1;MapPost(e,$"/outbound-webhooks/{{id}}/{action}",async(string id,EmptyWebhookCommand b,HttpContext c,OutboundWebhookService s,CancellationToken ct)=>{if(!TryCommand(c,true,out var m,out var error))return error!;var r=action switch{"activate"=>await s.Activate(id,m!,ct),"pause"=>await s.Pause(id,m!,ct),"resume"=>await s.Resume(id,m!,ct),"archive"=>await s.Archive(id,m!,ct),_=>await s.Rotate(id,m!,ct)};return Result(c,r);},x.Item2);}
 MapGet(e,"/outbound-webhook-deliveries",async(string? subscriptionId,HttpContext c,OutboundWebhookService s,CancellationToken ct)=>Result(c,await s.Deliveries(subscriptionId,Correlation(c),ct)),"listOutboundWebhookDeliveries");MapPost(e,"/outbound-webhook-deliveries/{id}/replay",async(string id,EmptyWebhookCommand b,HttpContext c,OutboundWebhookService s,CancellationToken ct)=>TryCommand(c,false,out var m,out var error)?Result(c,await s.ReplayDelivery(id,m!,ct)):error!,"replayOutboundWebhookDelivery");return e;}
 private static void MapGet(IEndpointRouteBuilder e,string p,Delegate h,string n)=>e.MapGet(p,h).RequireAuthorization().RequireTrustedWorkspace().WithName(n);private static void MapPost(IEndpointRouteBuilder e,string p,Delegate h,string n)=>e.MapPost(p,h).RequireAuthorization().RequireTrustedWorkspace().WithName(n);private static void MapPut(IEndpointRouteBuilder e,string p,Delegate h,string n)=>e.MapPut(p,h).RequireAuthorization().RequireTrustedWorkspace().WithName(n);
 private static string Correlation(HttpContext c)=>c.Request.Headers["X-Correlation-Id"].ToString() is{Length:>=8 and<=128} x?x:c.TraceIdentifier;private static bool TryCommand(HttpContext c,bool version,out WebhookCommandContext? command,out IResult? error){command=null;error=null;var key=c.Request.Headers["Idempotency-Key"].ToString();long? expected=null;if(key.Length is<8 or>128){error=Problem(c,"VALIDATION_FAILED",400);return false;}if(version){var value=c.Request.Headers.IfMatch.ToString();if(value.Length<3||value[0]!='"'||value[^1]!='"'||!long.TryParse(value[1..^1],NumberStyles.None,CultureInfo.InvariantCulture,out var parsed)||parsed<0){error=Problem(c,"VALIDATION_FAILED",400);return false;}expected=parsed;}command=new(key,expected,Correlation(c));return true;}
 private static IResult Result<T>(HttpContext c,WebhookResult<T> r) where T : class {if(!r.IsSuccess)return Problem(c,r.Code!,r.Status);if(r.Value is OutboundWebhookMutationResponse m)c.Response.Headers.ETag=$"\"{m.Subscription.Version}\"";else if(r.Value is OutboundWebhookSubscriptionDocument subscription)c.Response.Headers.ETag=$"\"{subscription.Version}\"";return Results.Json(r.Value,statusCode:r.Status);}
 private static IResult Problem(HttpContext c,string code,int status)=>Results.Json(new{type=$"urn:unicore:error:{code.ToLowerInvariant()}",title=code.Replace('_',' '),status,code,retryable=false,correlationId=Correlation(c)},statusCode:status,contentType:"application/problem+json");}
