namespace UnicoreCRM.Platform.AccessControl.Application.CreateAccessRole;

/// <summary>
/// Immutable runtime projection of capability-authorization-matrix.json filtered by the frozen
/// createAccessRole assignability rule at the active Design Authority baseline.
/// </summary>
internal static class AssignableCapabilityCatalog
{
    private static HashSet<string> Values { get; } = new(StringComparer.Ordinal)
    {
        "access.configure",
        "access.read",
        "contacts.read",
        "customers.view",
        "deals.assign",
        "deals.bulk",
        "deals.close",
        "deals.create",
        "deals.delete",
        "deals.read",
        "deals.update",
        "invoices.create",
        "invoices.create_credit_note",
        "invoices.issue",
        "invoices.read",
        "invoices.send",
        "invoices.update_draft",
        "invoices.void",
        "leads.assign",
        "leads.bulk",
        "leads.create",
        "leads.delete",
        "leads.export",
        "leads.qualify",
        "leads.read",
        "leads.update",
        "orders.complete",
        "orders.confirm",
        "orders.create",
        "orders.credit_approval.decide",
        "orders.credit_approval.request",
        "orders.delete",
        "orders.read",
        "orders.update",
        "organizations.read",
        "payments.allocate",
        "payments.intent.cancel",
        "payments.intent.create",
        "payments.plan.activate",
        "payments.plan.read",
        "payments.plan.supersede",
        "payments.plan.update_draft",
        "payments.read",
        "payments.reconcile",
        "payments.record_manual",
        "payments.refund",
        "payments.reverse_allocation",
        "products.create",
        "products.delete",
        "products.read",
        "quotes.approve",
        "quotes.create",
        "quotes.delete",
        "quotes.read",
        "quotes.update",
        "receivables.read",
        "returns.read",
        "returns.resolve",
        "returns.update",
        "shipping.create",
        "shipping.read",
        "studio.read",
        "support.assign",
        "support.create",
        "support.read",
        "support.update",
        "tasks.assign",
        "tasks.complete",
        "tasks.create",
        "tasks.read",
        "tasks.update",
        "workspace.context.resolve"
    };

    internal static bool Contains(string capability) => Values.Contains(capability);
}
